### PR TITLE
Add support of the nvidia-bluefield platform to generate-dump utility.

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**
#### What I did
Add support of the nvidia-bluefield platform to generate-dump utility to collect platform-specific dumps on NVIDIA Bluefield DPU.

#### How I did it
Extend platform-specific section of generate-dump utility

#### How to verify it
Run "show techsupport" command to generate dump file. Verify that `platform-dump` directory exists in the created dump file.

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Review by qiluo-msft — APPROVED** [review]

**Comment by qiluo-msft** [comment]
@xumia I believe the new code is not covered by testcase, why PR checker could not detect?

**Comment by xumia** [comment]
> @xumia I believe the new code is not covered by testcase, why PR checker could not detect?

Bash script is not supported yet.

**Comment by qiluo-msft** [comment]
@oleksandrivantsiv Could you consider a sonic-mgmt test case? Could you also attach the test case output?

**Comment by oleksandrivantsiv** [comment]
@qiluo-msft we have a sonic-mgmt test for this and will upstream it together with the rest DPU SONiC changes.

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
