### PR TITLE
Upgrade pyroute2 and improve cli response time

### PR DESCRIPTION
**Pull request by vivekrnv**
#### What I did

- Older pyroute2 depends on distutils. Thus upgrade the version to latest to improve import time. A similar issue for natsort is reported here https://github.com/sonic-net/sonic-buildimage/issues/17246. However pyroute2 import is still heavy in bookworm and thus every CLI command is slow compared to bullseye. 

```
<Bullseye>
root@msn2700:/home/admin# time python3 -c "import pyroute2"
real	0m0.378s
user	0m0.308s
sys	0m0.060s

<Before upgrade>
root@msn2700:/home/admin# time python3 -c "import pyroute2"
real        0m0.707s
user        0m0.425s
sys        0m0.097s

<After upgrade>
root@msn2700:/home/admin#  time python3 -c "import pyroute2"
real	0m0.511s
user	0m0.433s
sys	0m0.075s
```

- To fix this, i've delayed the pyroute2 import into the method where it is actually used, this has an improvement of 0.4 sec for all the CLI commands on slower CPU devices

```
root@msn2700:/home/admin#  time python3 -c "import utilities_common.cli as clicommon"
real	0m0.693s
user	0m0.579s
sys	0m0.109s

root@msn2700/home/admin#  time python3 -c "import utilities_common.cli as clicommon"
real	0m0.363s
user	0m0.271s
sys	0m0.072s
```

### CODE REVIEW

**Review by saiarcot895 — DISMISSED** [review]

**Comment by vivekrnv** [comment]
@qiluo-msft Requesting waiver to ignore the coverage failure. 

I tried adding an UT to cover the multi_asic_get_ip_intf_from_ns and multi_asic_get_ip_intf_addr_from_ns methods (https://github.com/sonic-net/sonic-utilities/commit/50e311ade00e8f78275f31b8e1e4fda3d3482d2a) .  

But these are monkey patched here https://github.com/sonic-net/sonic-utilities/blob/master/tests/mock_tables/mock_multi_asic.py#L93. 

So i couldn't call the actual method to capture it under the coverage scan. Besides, my changes just change the location of import and so no major functionality change that warrants a UT

**Review by keboliu — APPROVED** [review]

**Review by saiarcot895 — APPROVED** [review]

**Review by qiluo-msft — APPROVED** [review]

**Comment by qiluo-msft** [comment]
Thanks for the UT effort! Could you further explore if you can just disable multi_asic_get_ip_intf_from_ns monkey patch in your specific testcase? We should not globally enable one function monkey patch, because it will prevent us to UT the the function itself.

---
In reply to: [2330382035](https://github.com/sonic-net/sonic-utilities/pull/3513#issuecomment-2330382035) [](http://example.com/codeflow?ancestors=2330382035)

**Comment by vivekrnv** [comment]
> Thanks for the UT effort! Could you further explore if you can just disable multi_asic_get_ip_intf_from_ns monkey patch in your specific testcase? We should not globally enable one function monkey patch, because it will prevent us to UT the the function itself.
> 
> In reply to: [2330382035](https://github.com/sonic-net/sonic-utilities/pull/3513#issuecomment-2330382035)

Hi, i checked but monkey patching is global. once the file is imported and loaded, the original api is lost. 

I suppose this can be updated but changing this would also probably require some other Multi Asic UT's to also be updated and so i think this should be taken as a separate item

**Comment by bingwang-ms** [comment]
@vivekrnv Can you raise a PR to do the cherry-pick to 202405 since automation is not working?

**Pull request merged**
