### PR TITLE
Clear fabric counters queue/port

### PR DESCRIPTION
**Pull request by jfeng-arista**
Added two clear commands for fabric counters queue and fabric counters port.

sonic-clear fabriccountersport
sonic-clear fabriccountersqueue

By issuing the command, the fabric counters are clear and saved.  An example is as follow.

```
# show fabric counters port
  ASIC    PORT    STATE    IN_CELL    IN_OCTET    OUT_CELL    OUT_OCTET    CRC    FEC_CORRECTABLE    FEC_UNCORRECTABLE    SYMBOL_ERR
------  ------  -------  ---------  ----------  ----------  -----------  -----  -----------------  -------------------  ----------
...
     0      49       up          1         244           0            0       0                  2        2,372,752,496               0
     0      50       up          2         315           1          135       0                  4        2,522,457,120               4
...

# sonic-clear fabriccountersport
Clear and update saved counters port

# show fabric counters port
  ASIC    PORT    STATE    IN_CELL    IN_OCTET    OUT_CELL    OUT_OCTET    CRC    FEC_CORRECTABLE    FEC_UNCORRECTABLE    SYMBOL_ERR
------  ------  -------  ---------  ----------  ----------  -----------  -----  -----------------  -------------------  ------------
...
    0      49       up          0           0           0            0      0                  0                    0             0
    0      50       up          0           0           0            0      0                  0                    0             0

```

### CODE REVIEW

**Review by arlakshm — APPROVED** [review]

**Comment by gechiang** [comment]
I have a question about this new sonic-clear command.
Does it only clear counter for the user that logged in and cleared it so that if other users logged in with their own credential, they will still be able to see the original counts?  or this clear will clear it "globally" and all other users using different credentials will also see the cleared result?

**Comment by jfeng-arista** [comment]
> I have a question about this new sonic-clear command. Does it only clear counter for the user that logged in and cleared it so that if other users logged in with their own credential, they will still be able to see the original counts? or this clear will clear it "globally" and all other users using different credentials will also see the cleared result?

when I tested, it clears counters for the user that logged in.  Other users are still able to see the original counters.

**Comment by kenneth-arista** [comment]
@arlakshm can we merge this PR before the 202305 cut off?

**Comment by ridahanif96** [comment]
WhatsApp Image 2023-06-16 at 5 22 59 PM
 @kenneth-arista can you please fix these test cases? they are causing build issues in PR #2419  which is part of 202305.
@arlakshm can you please help?

**Comment by kenneth-arista** [comment]
> 

@ridahanif96 these test failures only hitting your PR or are they hitting generically? These tests were passing.

**Comment by ridahanif96** [comment]
> > 
> 
> @ridahanif96 these test failures only hitting your PR or are they hitting generically? These tests were passing.

they were hitting generally and affecting the master branch, but these are resolved by PR #2882  . Thanks @kenneth-arista

**Comment by gechiang** [comment]
@jfeng-arista , @arlakshm , I see this PR was later reverted.  Is there any plan to fix this or a new PR will be raised that has the feature and address the test failures soon?  Please clarify...
Perhaps we should remove the label "Chassis for 202205 branch" from this PR so we don't accidentally pick it up and introduce issues...

**Comment by arlakshm** [comment]
Thanks @gechiang  for checking on this. I removed the label

**Comment by kenneth-arista** [comment]
We'll create a new PR to resubmit the changes. Jie has been on FTA but will be back soon.

**Comment by StormLiangMS** [comment]
@jfeng-arista @gechiang this PR cause UT failed can't merge into 202305, pls recreate PR for 202305 and make sure UT get passed. 

=========================== short test summary info ============================
FAILED tests/fabricstat_test.py::TestFabricStat::test_single_show_fabric_counters
FAILED tests/fabricstat_test.py::TestFabricStat::test_single_clear_fabric_counters
FAILED tests/fabricstat_test.py::TestMultiAsicFabricStat::test_multi_show_fabric_counters_queue_clear
FAILED tests/fabricstat_test.py::TestMultiAsicFabricStatCmd::test_clear_command

**Comment by kenneth-arista** [comment]
> @jfeng-arista @gechiang this PR cause UT failed can't merge into 202305, pls recreate PR for 202305 and make sure UT get passed.
> 
> =========================== short test summary info ============================ FAILED tests/fabricstat_test.py::TestFabricStat::test_single_show_fabric_counters FAILED tests/fabricstat_test.py::TestFabricStat::test_single_clear_fabric_counters FAILED tests/fabricstat_test.py::TestMultiAsicFabricStat::test_multi_show_fabric_counters_queue_clear FAILED tests/fabricstat_test.py::TestMultiAsicFabricStatCmd::test_clear_command

@StormLiangMS the new PR that addresses the UT failures is https://github.com/sonic-net/sonic-utilities/pull/2892

**Pull request merged**
