### PR TITLE
Revert "Secure upgrade"

### PR DESCRIPTION
**Pull request by StormLiangMS**
Reverts sonic-net/sonic-utilities#2337

### CODE REVIEW

**Comment by ycoheNvidia** [comment]
Please consider assisting to push https://github.com/sonic-net/sonic-utilities/pull/2646 instead of this revert

**Comment by liat-grozovik** [comment]
please dont revert this PR but take a fix already avaialble.

**Comment by prgeor** [comment]
> please dont revert this PR but take a fix already avaialble.

@liat-grozovik @ycoheNvidia  please address comment on the fix PR

**Comment by StormLiangMS** [comment]
@liat-grozovik @ycoheNvidia pls have the fix PR comments resolved and merge soon, this one is blocking our nightly testing for one week.

**Comment by StormLiangMS** [comment]
@liat-grozovik  @ycoheNvidia  I see the fix PR comments from Qi is not addressed yet, I will do the revert to unblock the nightly for now.

**Pull request merged**
