### PR TITLE
[mmuconfig] Purge redundant mmuconfig file

### PR DESCRIPTION
**Pull request by arista-hpandya**
#### What I did
I removed the mmuconfig script under sonic-utilities which was orginally added in #2775 . This is because I noticed that this was potentially redundant as all scripts including mmuconfig are stored under the scripts/ folder. Additionally I believe this was a debug file which was not meant to be merged as I notice that there are pdb traces in this file.

#### How I did it
Purge the file

#### How to verify it
I verified that it was redundant by running the unit tests for sonic-utilities and comparing the file contents to the scripts/mmuconfig file.

#### Previous command output (if the output of a command-line utility has changed)
NA

#### New command output (if the output of a command-line utility has changed)
NA

### CODE REVIEW

**Comment by arista-hpandya** [comment]
@alpeshspatel Can you confirm if this file is not being used and is safe to purge?

**Comment by alpeshspatel** [comment]
the top level file (with pdb import) seems got added by mistake. yes ok to remove - Thanks!

**Comment by arista-hpandya** [comment]
Just a gentle nudge for a reviewer to review/merge it.

**Comment by kenneth-arista** [comment]
@arlakshm @wenyiz2021 can you help merge this cleanup fix?

**Review by kenneth-arista — APPROVED** [review]
Looks good to me

**Review by wenyiz2021 — APPROVED** [review]

**Comment by maipbui** [comment]
close and reopen to trigger Semgrep

**Pull request merged**
