### PR TITLE
[syslog] Adjust runningconfiguration syslog command

### PR DESCRIPTION
**Pull request by fastiuk**
#### What I did
Adjust `show runningconfiguration syslog` command according to the new syslog configuration file

#### How I did it
Fix regex to match the target syslog server

#### How to verify it
Run the next command in sonic shell:
```
show runningconfiguration syslog
```

#### Previous command output (if the output of a command-line utility has changed)
N/A

#### New command output (if the output of a command-line utility has changed)
N/A

### CODE REVIEW

**Review by wen587 — DISMISSED** [review]

**Comment by fastiuk** [comment]
@wen587 yes, it will

**Review by dgsudharsan — APPROVED** [review]

**Comment by dgsudharsan** [comment]
> @wen587 yes, it will

We need to do submodule update in the sonic-buildimage PR of rsyslog to avoid any break

**Review by wen587 — APPROVED** [review]

**Comment by fastiuk** [comment]
Rebased to master due to conflicts.
@wen587 / @dgsudharsan please reapprove

**Review by dgsudharsan — DISMISSED** [review]

**Comment by fastiuk** [comment]
> > @wen587 yes, it will
> 
> We need to do submodule update in the sonic-buildimage PR of rsyslog to avoid any break

added

**Review by dgsudharsan — APPROVED** [review]

**Comment by StormLiangMS** [comment]
This PR will cause PR test failure, revert from 202305. @fastiuk pls fix and have separate PR to 202305

==================================== ERRORS ====================================
______________ ERROR at teardown of test_syslog_server_tc1_suite _______________

duthosts = [<MultiAsicSonicHost vlab-01>], rand_one_dut_hostname = 'vlab-01'
original_syslog_servers = ['10.0.0.5', '10.0.0.6']

    @pytest.fixture(autouse=True)
    def setup_env(duthosts, rand_one_dut_hostname, original_syslog_servers):
        """
        Setup/teardown fixture for syslog config
        Args:
            duthosts: list of DUTs.
            rand_selected_dut: The fixture returns a randomly selected DuT.
            original_syslog_servers: original syslog servers stored in config
        """
        duthost = duthosts[rand_one_dut_hostname]
        create_checkpoint(duthost)
    
        yield
    
        try:
            logger.info("Rolled back to original checkpoint")
            rollback_or_reload(duthost)
    
            current_syslog_servers = get_current_syslog_servers(duthost)
>           pytest_assert(
                set(current_syslog_servers) == set(original_syslog_servers),
                "Syslog servers are not rollback_or_reload to initial config setup"
            )
E           Failed: Syslog servers are not rollback_or_reload to initial config setup

**Pull request merged**
