### PR TITLE
[202211] [db_migrator.py] Fix issue while upgrading from 202205 to 202211 via fast reboot

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Backport https://github.com/sonic-net/sonic-utilities/pull/2948 to 202211

#### What I did

Fix issue while upgrading from 202205 to 202211 via fast reboot. This issue is caused by a mismatch version handling for fast reboot in db_migrator. 

In 202205, the db migrator for fast reboot flag handling is 3_0_5:

https://github.com/sonic-net/sonic-utilities/blob/56a1ae24dc8f4e2dd2ad8929506ecdc836d3dd7c/scripts/db_migrator.py#L920

However, in master(202211), the db migrator for fast reboot flag handling is 4_0_0:

https://github.com/sonic-net/sonic-utilities/blob/7435b1ca539382e644f29d424c551f6258fd2920/scripts/db_migrator.py#L993

This mismatch causes an incorrect sequence like this:

```
1. User issue fast-reboot under 202205
2. fast-reboot script set fast reboot flag by command "sonic-db-cli STATE_DB HSET "FAST_RESTART_ENABLE_TABLE|system" "enable" "true" &>/dev/null"
3. system boot to 202211
4. db_migrator found the database version is 3_0_6, it will run 4_0_0, however, it found FAST_REBOOT|system does not exist, and it set  FAST_RESTART_ENABLE_TABLE|system enable to false
5. system incorrectly performs cold reboot
```

#### How I did it

in db migrator if we see there is FAST_RESTART_ENABLE_TABLE already, we should skip fast reboot flag migration

#### How to verify it

unit test
manual test

### CODE REVIEW

**Review by vaibhavhd — APPROVED** [review]

**Review by keboliu — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
Hi @StormLiangMS , could you please help merge this?

**Comment by Junchao-Mellanox** [comment]
Hi @StormLiangMS , could you please help merge this?

**Comment by Junchao-Mellanox** [comment]
Hi @StormLiangMS , could you please help merge this PR?

**Pull request merged**
