### PR TITLE
[Mellanox] Update C256X1 SKU to be C256S1 in gcu_field.json (#3611)

### PR DESCRIPTION
**Pull request by noaOrMlnx**
Update Mellanox-SN5600-C256X1 to be Mellanox-SN5600-C256S1 in gcu_field_operation_validators.conf.json

#### What I did
cherry pick to https://github.com/sonic-net/sonic-utilities/pull/3611
Update Mellanox-SN5600-C256X1 to be Mellanox-SN5600-C256S1 in gcu_field_operation_validators.conf.json

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@bingwang-ms  please help to merge

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@noaOrMlnx Please handle conflict if the code is needed for 202405.

**Comment by noaOrMlnx** [comment]
@bingwang-ms fixed

**Comment by bingwang-ms** [comment]
No file is changed. Probably the change has been merged by another PR. Please double check

**Comment by noaOrMlnx** [comment]
@bingwang-ms correct. I added 2 PRs that change the same line. please check this PR you just merged before conflicts were shown here - https://github.com/sonic-net/sonic-utilities/pull/3616

**Comment by noaOrMlnx** [comment]
@bingwang-ms that's because the first PR you merged contained the fix already - https://github.com/sonic-net/sonic-utilities/pull/3616

then this PR can be closed

**Pull request closed without merging**
