### PR TITLE
Add W-ECMP CLI

### PR DESCRIPTION
**Pull request by nazariig**
**HLD:** https://github.com/sonic-net/SONiC/pull/1629

#### What I did
* Implemented CLI for Weighted-Cost Multi-Path feature

#### How I did it
* Integrated Weighted-Cost Multi-Path interface into `config` and `show` CLI root

#### How to verify it
1. Run Weighted-Cost Multi-Path CLI UTs

#### Previous command output (if the output of a command-line utility has changed)
* N/A

#### New command output (if the output of a command-line utility has changed)
```
admin@sonic:/home/admin# show bgp device-global
TSA      WCMP
-------  -------
enabled  enabled
admin@sonic:/home/admin# show bgp device-global --json
{
    "tsa": "enabled",
    "wcmp": "enabled"
}
```

### CODE REVIEW

**Review by stepanblyschak — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@venkatmahalingam would you mind to provide code PR review feedback as well?

**Comment by tjchadaga** [comment]
@nazariig -  what is the expected output of the CLI on a multi-asic device?

**Comment by tjchadaga** [comment]
@nazariig - could you please clarify why TSA and WCMP are combined here, instead of a CLI dedicated to WCMP?

**Comment by nazariig** [comment]
> @nazariig - what is the expected output of the CLI on a multi-asic device?

@tjchadaga multi-asic is out of scope

**Comment by nazariig** [comment]
> @nazariig - could you please clarify why TSA and WCMP are combined here, instead of a CLI dedicated to WCMP?

They use the same configuration key and both are global features, so were put on the same table.

**Comment by tjchadaga** [comment]
> > @nazariig - could you please clarify why TSA and WCMP are combined here, instead of a CLI dedicated to WCMP?
> 
> @tjchadaga they use the same configuration key and both are global features, so were put on the same table.

@nazariig - would this CLI output need to be updated each time new bgp global features are added?

**Comment by nazariig** [comment]
> > > @nazariig - could you please clarify why TSA and WCMP are combined here, instead of a CLI dedicated to WCMP?
> > 
> > 
> > @tjchadaga they use the same configuration key and both are global features, so were put on the same table.
> 
> @nazariig - would this CLI output need to be updated each time new bgp global features are added?

@tjchadaga if the original YANG model is going to be reused and extended - the answer is yes

**Review by tjchadaga — APPROVED** [review]

**Pull request merged**
