### PR TITLE
[dns] Implement config and show commands for static DNS.

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**
#### What I did

Implement config and show commands for static DNS feature. According to https://github.com/sonic-net/SONiC/pull/1262 HLD.

#### How I did it

Static DNS config commands are implemented in the new config/dns.py file. DNS config commands are available under `config dns ...` sub-command.
Show commands are implemented in the new show/dns.py file. DNS show commands are available under `show dns ...` sub-command.

#### How to verify it
Compile sonic-utilities package. The unit tests will run automatically during the compilation.
Coverage for config/dns.py : 94%
Coverage for show/dns.py : 86%
#### New command output (if the output of a command-line utility has changed)
```
# config dns nameserver add 1.1.1.1
# config dns nameserver add 8.8.8.8
# show dns nameserver
  Nameserver
------------
     1.1.1.1
     8.8.8.8

```

### CODE REVIEW

**Review by Yakiv-Huryk — APPROVED** [review]

**Review by isabelmsft — CHANGES_REQUESTED** [review]
Hi @oleksandrivantsiv , thanks for your work on this PR and the DNS yang model. 

Since we are in the process of replacing adhoc validation checks (like your function `def is_valid_ip_address) with yang validation, could you please update your PR to reflect this? 

Here is the design doc for how we are phasing in yang validation: https://github.com/sonic-net/SONiC/pull/1072

Here is a sample PR to demonstrate changes that would be necessary to your PR: https://github.com/sonic-net/sonic-utilities/pull/2604

On a high level, the main steps are: 
1. add `if ADHOC_VALIDATION:` where you currently have adhoc validation
2. use the `ValidatedConfigDBConnector` decorator

**Review by ganglyu — APPROVED** [review]

**Comment by oleksandrivantsiv** [comment]
> Hi @oleksandrivantsiv , thanks for your work on this PR and the DNS yang model.
> 
> Since we are in the process of replacing adhoc validation checks (like your function `def is_valid_ip_address`) with yang validation, could you please update your PR to reflect this?
> 
> Here is the design doc for how we are phasing in yang validation: [sonic-net/SONiC#1072](https://github.com/sonic-net/SONiC/pull/1072)
> 
> Here is a sample PR to demonstrate changes that would be necessary to your PR: #2604
> 
> On a high level, the main steps are:
> 
> 1. add `if ADHOC_VALIDATION:` where you currently have adhoc validation
> 2. use the `ValidatedConfigDBConnector` decorator

@isabelmsft done

**Comment by liat-grozovik** [comment]
@isabelmsft could you please help to review following comments handled?

**Comment by oleksandrivantsiv** [comment]
@isabelmsft kindly reminder to review

**Comment by liat-grozovik** [comment]
@zhangyanzhao as this should be part of 202305 can you please create a label for sonic-utilities?

**Review by isabelmsft — APPROVED** [review]

**Review by Yakiv-Huryk — APPROVED** [review]

**Review by liat-grozovik — CHANGES_REQUESTED** [review]
@oleksandrivantsiv you are missing the command line reference update with the new commands. can you please update it and add the changes to this PR

**Comment by oleksandrivantsiv** [comment]
> @oleksandrivantsiv you are missing the command line reference update with the new commands. can you please update it and add the changes to this PR

done

**Review by dgsudharsan — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
