### PR TITLE
[pbh]: Fix show PBH counters when cache is partial

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

During system init the initial snapshot of PBH rule counters doesn't contain all the necessary information, which makes a dump invalid. Thus, it fails CLI to do a comparison logic which prints a traceback. After some time, when counters are getting updated in the DB, the snapshot can be taken correctly and the issue is gone.

#### What I did
* Fixed PBH CLI output when counter's cache is partial

#### How I did it
* Added additional constraint

#### How to verify it
1. Reboot the switch
2. Run `sonic-clear pbh statistics`
3. Run `show pbh statistics`

#### Previous command output (if the output of a command-line utility has changed)
```
root@sonic:/home/admin# show pbh statistics
Traceback (most recent call last):
  File "/usr/local/bin/show", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/show/plugins/pbh.py", line 386, in PBH_STATISTICS
    get_counter_value(pbh_counters, saved_pbh_counters, key, COUNTER_PACKETS_ATTR),
  File "/usr/local/lib/python3.9/dist-packages/show/plugins/pbh.py", line 401, in get_counter_value
    new_value = int(pbh_counters[key][type]) - int(saved_pbh_counters[key][type])
KeyError: 'SAI_ACL_COUNTER_ATTR_PACKETS'
```

#### New command output (if the output of a command-line utility has changed)
```
root@sonic:/home/admin# show pbh statistics
TABLE      RULE             RX PACKETS COUNT    RX BYTES COUNT
---------  ---------------  ------------------  ----------------
pbh_table  nvgre_ipv4_ipv4  0                   0
pbh_table  nvgre_ipv4_ipv6  0                   0
pbh_table  nvgre_ipv6_ipv4  0                   0
pbh_table  nvgre_ipv6_ipv6  0                   0
pbh_table  vxlan_ipv4_ipv4  0                   0
pbh_table  vxlan_ipv4_ipv6  0                   0
pbh_table  vxlan_ipv6_ipv4  0                   0
pbh_table  vxlan_ipv6_ipv6  0                   0
```

### CODE REVIEW

**Comment by nazariig** [comment]
@qiluo-msft / @yxieca please help to review & merge

**Comment by liat-grozovik** [comment]
@nazariig you mean that while the cache is not fully available the printed value will be 0?

**Comment by nazariig** [comment]
> @nazariig you mean that while the cache is not fully available the printed value will be 0?

@liat-grozovik correct. If no cache - print the actual counter value. This is a simple fix.

**Review by yxieca — APPROVED** [review]

**Comment by yxieca** [comment]
@nazariig the change looks in the good direction. However, from the description, I am not 100% sure if there could be a race condition where the record is not none and still only have partial information? Your current change only protected against the record is none scenario.

Can you add a unit test?

I am okay with moving forward with unit test since it is protecting a valid scenario.

**Comment by nazariig** [comment]
> @nazariig the change looks in the good direction. However, from the description, I am not 100% sure if there could be a race condition where the record is not none and still only have partial information? Your current change only protected against the record is none scenario.
> 
> Can you add a unit test?
> 
> I am okay with moving forward with unit test since it is protecting a valid scenario.

@yxieca done

**Pull request merged**
