### PR TITLE
[build] Fix base OS compilation issue caused by incompatibility between urllib3 and requests packages

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**
#### What I did
Fix SONiC image compilation issue:
```
+ sudo LANG=C DOCKER_HOST= chroot ./fsroot-mellanox /usr/local/bin/generate_shutdown_order.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/requests/adapters.py", line 532, in send
    conn = self._get_connection(request, verify, proxies=proxies, cert=cert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/requests/adapters.py", line 400, in _get_connection
    conn = self.poolmanager.connection_from_host(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/urllib3/poolmanager.py", line 304, in connection_from_host
    return self.connection_from_context(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/urllib3/poolmanager.py", line 326, in connection_from_context
    raise URLSchemeUnknown(scheme)
urllib3.exceptions.URLSchemeUnknown: Not supported URL scheme http+docker
```

#### How I did it
Pin request version <= `<=2.31.0`.

#### How to verify it
Run SONiC image compilation.

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Review by dgsudharsan — APPROVED** [review]

**Comment by jusherma** [comment]
Can this be backported to 202305 too, please?

**Comment by krismarvell** [comment]
Can this be backported to 202211 as well ? Thank you

**Comment by yxieca** [comment]
@volodymyrsamotiy seems that we need separate PR for 202205 branch.

**Comment by krismarvell** [comment]
@yxieca should we raise a seperate PR for 202211 as well? Pls let me know how to go about it. We are using 202211 branch actively

**Comment by StormLiangMS** [comment]
hi @oleksandrivantsiv @dgsudharsan cherry pick conflict for 202305, could you file separate PR?

**Comment by dgsudharsan** [comment]
@StormLiangMS  We already have the PR open https://github.com/sonic-net/sonic-utilities/pull/3351

**Comment by volodymyrsamotiy** [comment]
> @volodymyrsamotiy seems that we need separate PR for 202205 branch.

@yxieca, I created 202205 PR - https://github.com/sonic-net/sonic-utilities/pull/3355 [cherry-pick][202205][build] Fix base OS compilation issue caused by incompatibility between urllib3 and requests packages (#3328)

**Comment by lizhijianrd** [comment]
@saiarcot895 I saw you upgraded docker to 7.1.0 to fix this issue: https://github.com/sonic-net/sonic-buildimage/pull/19181

Should we revert this PR? When I run sonic-utilities test, the env is installing requests=2.32.3 but current PR requires request<=2.32.0 so UT cannot run.

**Comment by saiarcot895** [comment]
@lizhijianrd I think it can be reverted, but as long as docker 7.1.0 is getting installed in the test environment. I don't know if that is the case here.

**Pull request merged**
