### PR TITLE
clear: Fix clear queuecounters to also clear VOQ counters

### PR DESCRIPTION
**Pull request by patrickmacarthur**
#### What I did

Fix a bug where the CLI command `sonic-clear queuecounters` would not clear the VOQ counters.

fixes sonic-net/sonic-buildimage#15198

#### How I did it

Added the command to clear the VOQ counters.

#### How to verify it

1. Start traffic on an interface on a specific queue.
2. Use `show queue counters` and `show queue counters --voq` to verify that the counters are non-zero.
3. Stop traffic on the interface.
4. Run `sonic-clear queuecounters`.
5. Repeat the show commands and ensure that the counters have been reset.

### CODE REVIEW

**Comment by kenneth-arista** [comment]
@wenyiz2021 @arlakshm

**Review by arlakshm — COMMENTED** [review]
@patrickmacarthur , can you add a unit test for this command

**Comment by maipbui** [comment]
Please merge latest master code to trigger Semgrep.

**Review by wenyiz2021 — APPROVED** [review]
LGTM

**Comment by patrickmacarthur** [comment]
@maipbui  @arlakshm The Semgrep task is still not running. I have rebased to the latest code since I was requested to.

**Comment by patrickmacarthur** [comment]
Looks like Semgrep succeeded so this is ready for review

**Comment by arlakshm** [comment]
can you resolve the conflict.

**Review by wenyiz2021 — APPROVED** [review]

**Review by arlakshm — APPROVED** [review]

**Pull request merged**
