### PR TITLE
Add FEC correctable and uncorrectable port stats

### PR DESCRIPTION
**Pull request by prgeor**
Signed-off-by: Prince George <prgeor@microsoft.com>

Added command line option to see FEC correctable, uncorrectable errors and symbol errors(aggregate of all lanes) 

#### New command output (if the output of a command-line utility has changed)

```
admin@sonic:~$ show interfaces counters --help
Usage: show interfaces counters [OPTIONS] COMMAND [ARGS]...

  Show interface counters

Options:
  -a, --printall
  -p, --period TEXT
  -i, --interface TEXT
  -d, --display [all]   Show internal interfaces  [default: all]
  -n, --namespace []    Namespace name or all
  --verbose             Enable verbose output
  -?, -h, --help        Show this message and exit.

Commands:
  detailed   Show interface counters detailed
  errors     Show interface counters errors
  fec-stats  Show interface counters fec-stats            <<<<
  rates      Show interface counters rates
  rif        Show interface counters
admin@sonic:~$ 
```

```
root@sonic:~# show interfaces counters fec-stats 
Last cached time was 2022-07-29 19:34:08.919717
      IFACE    STATE    FEC_CORR    FEC_UNCORR    FEC_SYMBOL_ERR
-----------  -------  ----------  ------------  ----------------
  Ethernet0        U     136,403            34                40
  Ethernet8        D           0             0                 0
 Ethernet16        U           0             0                 0
 Ethernet24        D           0             0                 0
 Ethernet32        D           0             0                 0
 Ethernet40        D           0             0                 0
 Ethernet48        D           0             0                 0
 Ethernet56        D           0             0                 0
 Ethernet64        D           0             0                 0
 Ethernet72        D           0             0                 0
 Ethernet80        D           0             0                 0
 Ethernet88        D           0             0                 0
 Ethernet96        D           0             0                 0
Ethernet104        D           0             0                 0
Ethernet112        D           0             0                 0
Ethernet120        D           0             0                 0
Ethernet128        D           0             0                 0
Ethernet136        D           0             0                 0
Ethernet144        D           0             0                 0
Ethernet152        D           0             0                 0
Ethernet160        D           0             0                 0
Ethernet168        D           0             0                 0
Ethernet176        D           0             0                 0
Ethernet184        D           0             0                 0
Ethernet192        D           0             0                 0
Ethernet200        D           0             0                 0
Ethernet208        D           0             0                 0
Ethernet216        D           0             0                 0
Ethernet224        D           0             0                 0
Ethernet232        D           0             0                 0
Ethernet240        D           0             0                 0
Ethernet248        D           0             0                 0
Ethernet256        D         N/A           N/A               N/A
Ethernet260        D         N/A           N/A               N/A
root@sonic:~#
```

```
root@sonic:~# show interfaces counters fec-stats -p 15
The rates are calculated within 15 seconds period
      IFACE    STATE    FEC_CORR    FEC_UNCORR    FEC_SYMBOL_ERR
-----------  -------  ----------  ------------  ----------------
  Ethernet0        U       6,000             0                 5
  Ethernet8        D           0             0                 0
 Ethernet16        U           0             0                 0
 Ethernet24        D           0             0                 0
 Ethernet32        D           0             0                 0
 Ethernet40        D           0             0                 0
 Ethernet48        D           0             0                 0
 Ethernet56        D           0             0                 0
 Ethernet64        D           0             0                 0
 Ethernet72        D           0             0                 0
 Ethernet80        D           0             0                 0
 Ethernet88        D           0             0                 0
 Ethernet96        D           0             0                 0
Ethernet104        D           0             0                 0
Ethernet112        D           0             0                 0
Ethernet120        D           0             0                 0
Ethernet128        D           0             0                 0
Ethernet136        D           0             0                 0
Ethernet144        D           0             0                 0
Ethernet152        D           0             0                 0
Ethernet160        D           0             0                 0
Ethernet168        D           0             0                 0
Ethernet176        D           0             0                 0
Ethernet184        D           0             0                 0
Ethernet192        D           0             0                 0
Ethernet200        D           0             0                 0
Ethernet208        D           0             0                 0
Ethernet216        D           0             0                 0
Ethernet224        D           0             0                 0
Ethernet232        D           0             0                 0
Ethernet240        D           0             0                 0
Ethernet248        D           0             0                 0
Ethernet256        D         N/A           N/A               N/A
Ethernet260        D         N/A           N/A               N/A
root@sonic:~# 
```

### CODE REVIEW

**Comment by prgeor** [comment]
```
root@sonic:~# show interfaces counters errors 
      IFACE    STATE    RX_ERR    RX_DRP    RX_OVR    TX_ERR    TX_DRP    TX_OVR    FEC_CORR    FEC_UNCORR
-----------  -------  --------  --------  --------  --------  --------  --------  ----------  ------------
  Ethernet0        U         0         6         0         0         0         0       4,087             0
  Ethernet8        U         0         6         0         0         0         0      41,309             0
 Ethernet16        D         0         0         0         0         0         0           0             0
 Ethernet24        D         0         0         0         0         0         0           0             0
 Ethernet32        D         0         0         0         0         0         0           0             0
 Ethernet40        D         0         0         0         0         0         0           0             0
 Ethernet48        D         0         0         0         0         0         0           0             0
 Ethernet56        D         0         0         0         0         0         0           0             0```

**Comment by lguohan** [comment]
please add -v option to print out those column, not sure we should print them out by default.

**Comment by prgeor** [comment]
> please add -v option to print out those column, not sure we should print them out by default.

will add new option "fec-errors"

**Review by lguohan — APPROVED** [review]

**Comment by prgeor** [comment]
@yxieca can you help cherry pick this?

**Comment by prgeor** [comment]
@StormLiangMS can you help cherry pick this?

**Comment by StormLiangMS** [comment]
@prgeor  cherry pick to 202305 got conflicts, could you resubmit PR to 202305?

**Comment by prgeor** [comment]
@StormLiangMS the code changes are already in 202305

**Pull request merged**
