### PR TITLE
[GCU] Add PFC_WD RDMA validator 

### PR DESCRIPTION
**Pull request by isabelmsft**
Backport previous PR https://github.com/sonic-net/sonic-utilities/pull/2619/files to 202205

### CODE REVIEW

**Comment by yxieca** [comment]
@isabelmsft  can you solve the conflict and look into the test failures?

**Comment by qiluo-msft** [comment]
Semgrep warning can be skipped, because there is input validation for `import_module`.

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
