### PR TITLE
Revert "Switch Port Modes and VLAN CLI Enhancement (#2419)"

### PR DESCRIPTION
**Pull request by qiluo-msft**
#### What I did
Revert "Switch Port Modes and VLAN CLI Enhancement (#2419)".
The reason is PORT/mode is not yang modelled.

### CODE REVIEW

**Comment by qiluo-msft** [comment]
@ridahanif96 Please help review.

**Review by yxieca — APPROVED** [review]

**Comment by 2tu** [comment]
so, how to change port mode to trunk or access and hybrid?

**Comment by ridahanif96** [comment]
switchport mode can be changed using "config switch mode trunk/access Portname". Currently there is no hybrid port mode. Please see [HLD PR](https://github.com/sonic-net/SONiC/pull/912) for example details.

**Comment by 2tu** [comment]
> switchport mode can be changed using "config switch mode trunk/access Portname". Currently there is no hybrid port mode. Please see [HLD PR](https://github.com/sonic-net/SONiC/pull/912) for example details.

sorry, I'm not understand.
I'm a beginner learning SONiC.

I can't find "switch" command in [Command-Reference.](https://github.com/sonic-net/sonic-utilities/blob/master/doc/Command-Reference.md)

**Comment by ridahanif96** [comment]
> > switchport mode can be changed using "config switch mode trunk/access Portname". Currently there is no hybrid port mode. Please see [HLD PR](https://github.com/sonic-net/SONiC/pull/912) for example details.
> 
> sorry, I'm not understand. I'm a beginner learning SONiC.
> 
> I can't find "switch" command in [Command-Reference.](https://github.com/sonic-net/sonic-utilities/blob/master/doc/Command-Reference.md)

Yes, these commands are temporarily not available in command reference. We are on it and it will be soon available in SONiC for users.

**Comment by 2tu** [comment]
> > > switchport mode can be changed using "config switch mode trunk/access Portname". Currently there is no hybrid port mode. Please see [HLD PR](https://github.com/sonic-net/SONiC/pull/912) for example details.
> > 
> > 
> > sorry, I'm not understand. I'm a beginner learning SONiC.
> > I can't find "switch" command in [Command-Reference.](https://github.com/sonic-net/sonic-utilities/blob/master/doc/Command-Reference.md)
> 
> Yes, these commands are temporarily not available in command reference. We are on it and it will be soon available in SONiC for users.

I got this.
thank you very much.

**Pull request merged**
