### PR TITLE
Updated the CLIs for 202205 release

### PR DESCRIPTION
**Pull request by kannankvs**
Signed-off-by: kannankvs <kannan_kvs@dell.com>

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@kannankvs i am not able to see the diff as the file is too big. Could you please check this the changes?

**Review by xinliu-seattle — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@kannankvs could u please handle conflicts and we can then merge?

**Review by qiluo-msft — APPROVED** [review]

**Comment by qiluo-msft** [comment]
Please resolve conflict.

**Comment by qiluo-msft** [comment]
Could you resolve conflict again?

**Comment by kannankvs** [comment]
> Could you resolve conflict again?

Yes, the file has been updated for special characters to resolve conflicts.

**Comment by kannankvs** [comment]
Yes, the file has been updated for special characters to resolve conflicts.

**Comment by qiluo-msft** [comment]
@kannankvs As you can see "This branch has conflicts that must be resolved", could you check again?

**Comment by kannankvs** [comment]
@qiluo-msft Since the PR has branch conflict. We have raised a new [PR#2589](https://github.com/sonic-net/sonic-utilities/pull/2589) for the same. Will close the old [PR#2435](https://github.com/sonic-net/sonic-utilities/pull/2435) once the new PR is merged.

**Comment by qiluo-msft** [comment]
@kannankvs you can continue resolve conflict and update this PR, no need to raise another PR (I checked the new one, still not in a good shape).

**Comment by kannankvs** [comment]
Closing this PR with reference to [PR#2589](https://github.com/sonic-net/sonic-utilities/pull/2589) as this PR has conflicts.

**Pull request closed without merging**
