### PR TITLE
Fixes invalid namespace issues that would occur when making sfputil C…

### PR DESCRIPTION
**Pull request by bmridul**
#### What I did
Fixed invalid namespace issues that would occur when making sfputil CLI calls.

#### How I did it
Made a call to `load_db_config()` in `load_port_config()`

#### How to verify it
```bash
sfputil show presence
```

#### Previous command output (if the output of a command-line utility has changed)
```bash
root@sonic:/home/cisco# sfputil show presence
Error reading port info (:- validateNamespace: Initialize global DB config using API SonicDBConfig::initializeGlobalConfig)
```
#### New command output (if the output of a command-line utility has changed)
```bash
root@sonic:/home/cisco# sfputil show presence
Port        Presence
----------  -----------
Ethernet18  Not present
Ethernet38  Not present
Ethernet45  Not present
Ethernet41  Not present
Ethernet44  Not present
Ethernet47  Not present
Ethernet28  Not present
Ethernet36  Not present
Ethernet7   Present
Ethernet19  Not present
Ethernet16  Not present
Ethernet25  Not present
Ethernet29  Not present
Ethernet43  Not present
Ethernet32  Not present
Ethernet33  Not present
Ethernet11  Not present
Ethernet2   Not present
Ethernet10  Not present
Ethernet6   Present
Ethernet22  Not present
Ethernet42  Not present
Ethernet37  Not present
Ethernet5   Present
Ethernet30  Not present
Ethernet9   Not present
Ethernet14  Not present
Ethernet26  Not present
Ethernet46  Not present
Ethernet31  Not present
Ethernet35  Not present
Ethernet17  Not present
Ethernet4   Not present
Ethernet8   Present
Ethernet1   Not present
Ethernet20  Not present
Ethernet24  Not present
Ethernet23  Not present
Ethernet27  Not present
Ethernet40  Not present
Ethernet3   Not present
Ethernet12  Not present
Ethernet21  Not present
Ethernet0   Present
Ethernet39  Not present
Ethernet34  Not present
Ethernet13  Not present
Ethernet15  Not present
```

### CODE REVIEW

**Comment by bmridul** [comment]
@abdosi @rlhui

**Comment by abdosi** [comment]
@mlok-nokia can you please help review this

**Comment by mlok-nokia** [comment]
> @mlok-nokia can you please help review this
This is the same issue which I have created the PR for. 
https://github.com/sonic-net/sonic-utilities/pull/2373

**Comment by mlok-nokia** [comment]
@abdosi  The reason why I separated the "sudo sfputil show presence/eeprom" and "sudo sfputil show error-status" is:  There is no problem with ""sudo sfputil show presence/eeprom"" command on msft-2205 branch, this two command only occurs on Master branch.  The msft-2205 branch only has the "sudo sfputil show error-status" issue.

**Pull request closed without merging**
