### PR TITLE
[db_migrator]Remove route migration

### PR DESCRIPTION
**Pull request by dgsudharsan**
#### What I did

**Needs to be merged after https://github.com/sonic-net/sonic-swss/pull/2981**

Fix https://github.com/sonic-net/sonic-buildimage/issues/17322
Remove the route migration operation from db_migrator. The route migration operation takes a lot of time as indicated in the below issue. This is not necessary since the hardcoded assert in the fpmsyncd on new fields is removed in https://github.com/sonic-net/sonic-swss/pull/2981

#### How I did it
Removing the logic to migrate routes

#### How to verify it
Removed the necessary UT as well

### CODE REVIEW

**Review by stepanblyschak — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@StormLiangMS  Tested on top of 202305 commit https://github.com/sonic-net/sonic-buildimage/commit/688245a724e7462765530fd8ec3a745d7372dd5e

**Comment by dgsudharsan** [comment]
@StormLiangMS  Tested on top of 202305 commit https://github.com/sonic-net/sonic-buildimage/commit/688245a724e7462765530fd8ec3a745d7372dd5e

**Comment by liat-grozovik** [comment]
@yxieca could you please help to review or assign someone ?

**Review by yxieca — APPROVED** [review]

**Comment by yxieca** [comment]
Note: merge after https://github.com/sonic-net/sonic-buildimage/pull/17501 is merged.

**Comment by dgsudharsan** [comment]
@yxieca  @lguohan  @qiluo-msft  Can you please help merge this?

**Pull request merged**
