### PR TITLE
Change the default behavior of show ip bgp network

### PR DESCRIPTION
**Pull request by BYGX-wcr**
#### What I did

I changed the default behaviors of "show ip bgp network" command on multi-asic chassis.

#### How I did it

I modified the implementation of "bgp" command group and "network" subcommand in show/bgp_frr_v4.py and updated the relevant unit tests. The changes are listed below.

1. Now, by default "show ip bgp network" will display results from all namespaces. Meanwhile, it will not forcefully require "-n" option any more.
2. "show ip bgp network" now will require ip-address/ip-prefix option to be executed on chassis supervisors. This is to avoid getting excessive routes from such command on the supervisors.

#### How to verify it

Install and run it on a SONiC T2 chassis.

#### Previous command output (if the output of a command-line utility has changed)

Previously, if you run `show ip bgp network` on a chassis supervisor you will get something similar to below:
```
======== LINE-CARD0|lc1-hostname output: ========
Usage: show ip bgp network [OPTIONS] [<ipv4-address>|<ipv4-prefix>]
                           [bestpath|json|longer-prefixes|multipath]
Try "show ip bgp network -h" for help.

Error: -n/--namespace option required. provide namespace from list ['asic0', 'asic1']

======== LINE-CARD1|lc2-hostname output: ========
Usage: show ip bgp network [OPTIONS] [<ipv4-address>|<ipv4-prefix>]
                           [bestpath|json|longer-prefixes|multipath]
Try "show ip bgp network -h" for help.

Error: -n/--namespace option required. provide namespace from list ['asic0', 'asic1']

```

#### New command output (if the output of a command-line utility has changed)

Now, running `show ip bgp network` on a chassis supervisor will display:
```
Usage: show ip bgp network [OPTIONS] [<ipv4-address>|<ipv4-prefix>]
                           [bestpath|json|longer-prefixes|multipath]
Try "show ip bgp network -h" for help.

Error: Missing argument "[<ipv4-address>|<ipv4-prefix>]".
```
After you specify an ipv4 prefix or ipv4 address, then you will get:
```
======== LINE-CARD0|lc1-hostname output: ========

======== namespace asic0 ========
BGP routing table entry for 192.170.99.0/25, version 6085
Paths: (4 available, best #4, table default)
  65000 65506
    10.0.0.13 from 3.3.3.6 (192.0.0.6)
      Origin IGP, localpref 100, valid, internal, multipath
      AddPath ID: RX 229, TX-All 207 TX-Best-Per-AS 0
      Last update: Thu Jul 25 22:00:44 2024
  65003 65506
    10.0.0.23 from 3.3.3.8 (192.0.0.8)
      Origin IGP, localpref 100, valid, internal, multipath
      AddPath ID: RX 117, TX-All 726 TX-Best-Per-AS 0
      Last update: Thu Jul 25 00:15:58 2024
  65002 65506
    10.0.0.19 from 3.3.3.8 (192.0.0.8)
      Origin IGP, localpref 100, valid, internal, multipath
      AddPath ID: RX 375, TX-All 727 TX-Best-Per-AS 0
      Last update: Thu Jul 25 00:15:58 2024
  65001 65506
    10.0.0.17 from 3.3.3.6 (192.0.0.6)
      Origin IGP, localpref 100, valid, internal, multipath, best (Router ID)
      AddPath ID: RX 228, TX-All 206 TX-Best-Per-AS 0
      Advertised to: 10.0.0.1
      Last update: Thu Jul 25 00:15:57 2024

======== namespace asic1 ========
BGP routing table entry for 192.170.99.0/25, version 6087
Paths: (4 available, best #4, table default)
  65000 65506
    10.0.0.13 from 3.3.3.6 (192.0.0.6)
      Origin IGP, localpref 100, valid, internal, multipath
      AddPath ID: RX 229, TX-All 207 TX-Best-Per-AS 0
      Last update: Thu Jul 25 22:00:44 2024
  65003 65506
    10.0.0.23 from 3.3.3.8 (192.0.0.8)
      Origin IGP, localpref 100, valid, internal, multipath
      AddPath ID: RX 117, TX-All 727 TX-Best-Per-AS 0
      Last update: Thu Jul 25 00:15:58 2024
  65002 65506
    10.0.0.19 from 3.3.3.8 (192.0.0.8)
      Origin IGP, localpref 100, valid, internal, multipath
      AddPath ID: RX 375, TX-All 728 TX-Best-Per-AS 0
      Last update: Thu Jul 25 00:15:58 2024
  65001 65506
    10.0.0.17 from 3.3.3.6 (192.0.0.6)
      Origin IGP, localpref 100, valid, internal, multipath, best (Router ID)
      AddPath ID: RX 228, TX-All 206 TX-Best-Per-AS 0
      Advertised to: 10.0.0.7
      Last update: Thu Jul 25 00:15:57 2024

======== LINE-CARD1|lc2 output: ========

======== namespace asic0 ========
BGP routing table entry for 192.170.99.0/25, version 16554
Paths: (4 available, best #4, table default)
  65000 65506
    10.0.0.13 from 10.0.0.13 (100.1.0.7)
      Origin IGP, valid, external, multipath
      AddPath ID: RX 0, TX-All 229 TX-Best-Per-AS 0
      Advertised to: 3.3.3.1 3.3.3.2 3.3.3.8
      Last update: Thu Jul 25 22:00:45 2024
  65003 65506
    10.0.0.23 from 3.3.3.8 (192.0.0.8)
      Origin IGP, localpref 100, valid, internal, multipath
      AddPath ID: RX 117, TX-All 733 TX-Best-Per-AS 0
      Last update: Tue Jul 23 07:40:44 2024
  65002 65506
    10.0.0.19 from 3.3.3.8 (192.0.0.8)
      Origin IGP, localpref 100, valid, internal, multipath
      AddPath ID: RX 375, TX-All 734 TX-Best-Per-AS 0
      Last update: Tue Jul 23 07:40:44 2024
  65001 65506
    10.0.0.17 from 10.0.0.17 (100.1.0.9)
      Origin IGP, valid, external, multipath, best (Peer Type)
      AddPath ID: RX 0, TX-All 228 TX-Best-Per-AS 0
      Advertised to: 3.3.3.1 3.3.3.2 3.3.3.8
      Last update: Tue Jul 23 07:40:44 2024

======== namespace asic1 ========
BGP routing table entry for 192.170.99.0/25, version 16795
Paths: (4 available, best #4, table default)
  65000 65506
    10.0.0.13 from 3.3.3.6 (192.0.0.6)
      Origin IGP, localpref 100, valid, internal, multipath
      AddPath ID: RX 229, TX-All 733 TX-Best-Per-AS 0
      Last update: Thu Jul 25 22:00:44 2024
  65001 65506
    10.0.0.17 from 3.3.3.6 (192.0.0.6)
      Origin IGP, localpref 100, valid, internal, multipath
      AddPath ID: RX 228, TX-All 734 TX-Best-Per-AS 0
      Last update: Tue Jul 23 07:40:43 2024
  65002 65506
    10.0.0.19 from 10.0.0.19 (100.1.0.10)
      Origin IGP, valid, external, multipath
      AddPath ID: RX 0, TX-All 375 TX-Best-Per-AS 0
      Advertised to: 3.3.3.1 3.3.3.2 3.3.3.6
      Last update: Tue Jul 23 07:39:34 2024
  65003 65506
    10.0.0.23 from 10.0.0.23 (100.1.0.12)
      Origin IGP, valid, external, multipath, best (Older Path)
      AddPath ID: RX 0, TX-All 117 TX-Best-Per-AS 0
      Advertised to: 3.3.3.1 3.3.3.2 3.3.3.6
      Last update: Tue Jul 23 07:39:34 2024
```

### CODE REVIEW

**Review by wenyiz2021 — APPROVED** [review]
please paste the output from your validation in PR description.
LGTM

**Comment by gechiang** [comment]
@BYGX-wcr since there is a conflict that prevented auto merge to 202405, you will need to open a PR directly to the 202405 branch of this same Repo to manually merge your changes over and tag @wenyiz2021 to help review it again and @qiluo-msft to approve/merge on the 202405 branch.

I will let you know how it went with the MSFT repo cherry-pick whether it also require manual PR creation there or not...

**Comment by gechiang** [comment]
@BYGX-wcr , please create a MSFT ADO and share its number here.
Thanks!

**Comment by gechiang** [comment]
Here is the corresponding MSFT repo PR: https://github.com/sonic-net/sonic-utilities.msft/pull/86

**Comment by bingwang-ms** [comment]
@BYGX-wcr Can you file a PR for 202405 to address the conflict?

**Pull request merged**
