### PR TITLE
[actions]: Add CodeQL workflow status badge

### PR DESCRIPTION
**Pull request by mdanish-kh**
#### What I did
Add CodeQL workflow status badge to README.md as LGTM is deprecated.

### CODE REVIEW

**Comment by mdanish-kh** [comment]
@maipbui Could you please review?

**Comment by mdanish-kh** [comment]
@Blueve Could you please review?

**Comment by mdanish-kh** [comment]
@liat-grozovik Could you please review?

**Review by liat-grozovik — APPROVED** [review]
LGTM. on which active branches we want this to be used? should we have it on 202205 as well or just 202211 and above?

**Comment by mdanish-kh** [comment]
> LGTM. on which active branches we want this to be used? should we have it on 202205 as well or just 202211 and above?

Looks like it was recently added for `202205` and `202211` so it would be a good idea to add them as well. GitHub API doesn't seem to let me add a label for the badge, but I'll add them anyways in README.md

**Comment by mdanish-kh** [comment]
@liat-grozovik Kindly review again at your convenience

**Pull request closed without merging**
