### PR TITLE
[Nokia] Add J2C+/H3/H4/H5 to GCU validator

### PR DESCRIPTION
**Pull request by dgodwin-nokia**
* Add Nokia platforms to GCU validator .json file

#### What I did

Nokia J2C/TH3/4/5 based platforms were not included in the GCU field validators file. This caused some of the sonic-mgmt test cases to fail related to PFCWD/BUFFER_POOL/BUFFER_PROFILE/WRED due to apply-patch validation failing. Added the platforms.

This PR is required for 202405.

#### How to verify it

Validated that sonic-mgmt GCU tests now pass.

### CODE REVIEW

**Comment by mlok-nokia** [comment]
@prgeor  Hi Prince,  Could you please review this PR to assign it to the person?  Thanks

**Comment by xincunli-sonic** [comment]
Can you help provide more info, like any issue that is tracking sonic-mgmt test failure, also can you share the sonic-mgmt GCU tests passed details, Thanks!

**Comment by mlok-nokia** [comment]
@okaravasi Can you please address the comment above?

**Comment by okaravasi** [comment]
> Can you help provide more info, like any issue that is tracking sonic-mgmt test failure, also can you share the sonic-mgmt GCU tests passed details, Thanks!

Suggested changes are needed to pass below test suites:
 
- generic_config_updater/test_pg_headroom_update.py
- generic_config_updater/test_mmu_dynamic_threshold_config_update.py
- generic_config_updater/test_ecn_config_update.py
 
That they perform changes in cfg paths /BUFFER_PROFILE, /WRED_PROFILE.

**Comment by xincunli-sonic** [comment]
> > Can you help provide more info, like any issue that is tracking sonic-mgmt test failure, also can you share the sonic-mgmt GCU tests passed details, Thanks!
> 
> @xincunli-sonic Suggested changes are needed to pass below test suites:
> 
> * generic_config_updater/test_pg_headroom_update.py
> * generic_config_updater/test_mmu_dynamic_threshold_config_update.py
> * generic_config_updater/test_ecn_config_update.py
> 
> That they perform changes in cfg paths /BUFFER_PROFILE, /WRED_PROFILE.

Were they failing in 202405 or something else, do we have github issue tracking it? And as you mentioned in top description that you did pass these tests by the new change, can you share the output where took your change, Thanks!

**Comment by dgodwin-nokia** [comment]
> > > Can you help provide more info, like any issue that is tracking sonic-mgmt test failure, also can you share the sonic-mgmt GCU tests passed details, Thanks!
> > 
> > 
> > @xincunli-sonic Suggested changes are needed to pass below test suites:
> > 
> > * generic_config_updater/test_pg_headroom_update.py
> > * generic_config_updater/test_mmu_dynamic_threshold_config_update.py
> > * generic_config_updater/test_ecn_config_update.py
> > 
> > That they perform changes in cfg paths /BUFFER_PROFILE, /WRED_PROFILE.
> 
> Were they failing in 202405 or something else, do we have github issue tracking it? And as you mentioned in top description that you did pass these tests by the new change, can you share the output where took your change, Thanks!

@xincunli-sonic These tests have always failed for these platforms. The tests validate the ability to use "apply-patch" to modify configuration in these areas.

They will always fail for platforms that are not included in this file. "apply-patch" parses this file and checks that the current version is at least the version in the file before allowing patching of these areas.

**Review by judyjoseph — APPROVED** [review]

**Comment by mlok-nokia** [comment]
@judyjoseph  Could you please help to cherry-pick this PR to 202405?  Thanks

**Pull request merged**
