### PR TITLE
Update sonic-utilities to support new SKU Mellanox-SN5600-O128

### PR DESCRIPTION
**Pull request by stephenxs**
#### What I did

Update sonic-utilities to support new SKU Mellanox-SN5600-O128

1. Add the SKU to the generic configuration updater
2. Simplify the logic of the buffer migrator to support the new SKU

#### How to verify it

Manual and unit tests

### CODE REVIEW

**Review by keboliu — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Review by qiluo-msft — DISMISSED** [review]

**Comment by stephenxs** [comment]
Conflicts resolved.

**Comment by stephenxs** [comment]
@liat-grozovik  @qiluo-msft  can you approve and merge it? it was previously approved by you but I resolved conflicts, which dismissed approval.
thanks

**Review by qiluo-msft — APPROVED** [review]

**Comment by stephenxs** [comment]
Cherry-pick depends on #3272 @keboliu @liat-grozovik FYI.

**Comment by stephenxs** [comment]
Hi @yxieca 
It can be cherry-picked to 202311 without a conflict as the dependent PR has been merged.
Could you please help to cherry-pick it?
Thanks

**Pull request merged**
