### PR TITLE
[route_check][dualtor] Ignore vlan neighbor route miss

### PR DESCRIPTION
**Pull request by lolyu**
#### What I did
As the subject.
This PR is to leave the vlan neighbor route checking to `dualtor_neighbor_check.py` script: https://github.com/sonic-net/sonic-utilities/pull/2840

Signed-off-by: Longxiang Lyu <lolv@microsoft.com>

#### How I did it
If any misses are found on dualtor, ignore those vlan neighbor misses.

#### How to verify it
UT and verify on testbed.

### CODE REVIEW

**Review by prsunny — APPROVED** [review]
lgtm, @theasianpianist , please review as well

**Comment by prsunny** [comment]
@lolyu , can you please provide a link to the new PR that handles dualtor routes

**Comment by lolyu** [comment]
> @lolyu , can you please provide a link to the new PR that handles dualtor routes

Sure, this one: https://github.com/sonic-net/sonic-utilities/pull/2840

**Pull request merged**
