### PR TITLE
Added support to display only nonzero queue counter.

### PR DESCRIPTION
**Pull request by abdosi**
What I did:
Added new option `--nonzero` to display given {port,queue} or {system-port, voq} counter only if any of counter value is non zero.

Microsoft ADO: 24888995

Why I did:
Adding this option is useful during debugging specially on VOQ system that can have many {System port, Queue} on one LC running SONiC instance.

How I verify:
UT has been modified and updated
Manual Verification on chassis systems.

### CODE REVIEW

**Review by vmittal-msft — APPROVED** [review]

**Review by gechiang — APPROVED** [review]

**Comment by prsunny** [comment]
@abdosi , would you please provide output of the new command in description?

**Comment by StormLiangMS** [comment]
@abdosi cherry pick conflict, pls file separate PR for 202305.

**Comment by abdosi** [comment]
> @abdosi , would you please provide output of the new command in description?

updated.

**Comment by StormLiangMS** [comment]
@abdosi remind for conflict with 202305 cherry pick

**Comment by abdosi** [comment]
> @abdosi remind for conflict with 202305 cherry pick

@StormLiangMS 202305 PR: https://github.com/sonic-net/sonic-utilities/pull/3046

**Pull request merged**
