### PR TITLE
Techsupport tmpfs logging

### PR DESCRIPTION
**Pull request by mihirpat1**
#### What I did
It seems that "show techsupport" currently doesn't archive the log files under "/var/log.tmpfs" directory. Hence, this PR addresses this issue.

ADO - 25129114

#### How I did it
We are now checking if "/var/log.tmpfs" directory exists and include the corresponding log files.

#### How to verify it
1. "show techsupport" on a system with logging to "/var/log/"
2. "show techsupport" on a system with logging to "/var/log.tmpfs/"

```
**************************************************************
1. "show techsupport" on a system with logging to "/var/log/"
**************************************************************
path="/var/log/"
root@sonic:/tmp/tar# df -Th
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs  3.9G     0  3.9G   0% /dev
tmpfs          tmpfs     794M   16M  779M   2% /run
root-overlay   overlay    28G   27G  695M  98% /
/dev/sda1      ext4       28G   27G  695M  98% /host
/dev/loop1     ext4      3.9G  2.0G  1.7G  55% /var/log
tmpfs          tmpfs     3.9G   60K  3.9G   1% /dev/shm
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs     4.0M     0  4.0M   0% /sys/fs/cgroup
overlay        overlay    28G   27G  695M  98% /var/lib/docker/overlay2/07e08c792d322705d7aab531a4bbb6eeead1ad655146146afa54ca566115bbfd/merged
overlay        overlay    28G   27G  695M  98% /var/lib/docker/overlay2/04cedcfc8ec23e1c1a273277f426c81f7707752e861e22063e6a808873596dea/merged
overlay        overlay    28G   27G  695M  98% /var/lib/docker/overlay2/64109698132d7829c59e5f370260aa4c30be7d4e79680110290ea0c8f21f0041/merged
overlay        overlay    28G   27G  695M  98% /var/lib/docker/overlay2/2659cf45a8e5e7281cafe1a171ff23f5b38ea40d8cc9e8a7ade489ffbf223eb6/merged
overlay        overlay    28G   27G  695M  98% /var/lib/docker/overlay2/fe106c2d617a94ceb89934bea7bfd2f19108010f0af51455a8897e92a2a124d3/merged
overlay        overlay    28G   27G  695M  98% /var/lib/docker/overlay2/1338b1ccca099effe18e274d87cfff26907206a48c534dfe73d34408c254c3af/merged
overlay        overlay    28G   27G  695M  98% /var/lib/docker/overlay2/7e0ddc26d989c35fa1115b07a552bc882857e54b6876bedbd1ba4cd4066fba31/merged
overlay        overlay    28G   27G  695M  98% /var/lib/docker/overlay2/18b39941362f777aadadbeb0ccc9235469239c52ceb841065ab301c819fbe0ec/merged
overlay        overlay    28G   27G  695M  98% /var/lib/docker/overlay2/31304cc1dcb8844317c6d84f67c4a16231cb7566470128cd364e3e9b56a0ba74/merged
overlay        overlay    28G   27G  695M  98% /var/lib/docker/overlay2/40a7f85c913ee8cd7840a566d4082fe29db2d06bbac1a676e10cab39cc03395c/merged
overlay        overlay    28G   27G  695M  98% /var/lib/docker/overlay2/203339b29f19de43ae19dc9acafc9f3a4efea8e084b8b077a107d1e4c3cc8ab3/merged
overlay        overlay    28G   27G  695M  98% /var/lib/docker/overlay2/3972601076a8d3ed3d98ae705a6d09f7350f8c698d1b52402cd369b838b9c413/merged
overlay        overlay    28G   27G  695M  98% /var/lib/docker/overlay2/62a370c50dea32f9d5e6d834db76b85e8bb2af669a589e7be55bbe4df199e0c1/merged
root@sonic:/tmp/tar# 

Time taken to generate the "log" and "log.tmpfs" folder in archive
[ TAR /var/log Files ] : 86478 msec

File count at original log file location
root@sonic:/tmp/tar# find $path -type f | wc -l
4385

File count at extracted tar file location
root@sonic:/tmp/tar/sonic_dump_sonic_20230913_055541/log# find . -type f | wc -l
4384

**************************************************************
2. "show techsupport" on a system with logging to "/var/log.tmpfs/"
**************************************************************
path="/var/log.tmpfs/"
df -Th
root@sonic:/tmp/tar# df -Th
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs  3.9G     0  3.9G   0% /dev
tmpfs          tmpfs     794M   16M  779M   2% /run
root-overlay   overlay    28G   22G  6.2G  78% /
/dev/sda1      ext4       28G   22G  6.2G  78% /host
/dev/loop1     ext4      3.9G  2.0G  1.7G  55% /var/log
tmpfs          tmpfs     3.9G   60K  3.9G   1% /dev/shm
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs     4.0M     0  4.0M   0% /sys/fs/cgroup
overlay        overlay    28G   22G  6.2G  78% /var/lib/docker/overlay2/07e08c792d322705d7aab531a4bbb6eeead1ad655146146afa54ca566115bbfd/merged
overlay        overlay    28G   22G  6.2G  78% /var/lib/docker/overlay2/04cedcfc8ec23e1c1a273277f426c81f7707752e861e22063e6a808873596dea/merged
overlay        overlay    28G   22G  6.2G  78% /var/lib/docker/overlay2/64109698132d7829c59e5f370260aa4c30be7d4e79680110290ea0c8f21f0041/merged
overlay        overlay    28G   22G  6.2G  78% /var/lib/docker/overlay2/2659cf45a8e5e7281cafe1a171ff23f5b38ea40d8cc9e8a7ade489ffbf223eb6/merged
overlay        overlay    28G   22G  6.2G  78% /var/lib/docker/overlay2/fe106c2d617a94ceb89934bea7bfd2f19108010f0af51455a8897e92a2a124d3/merged
overlay        overlay    28G   22G  6.2G  78% /var/lib/docker/overlay2/1338b1ccca099effe18e274d87cfff26907206a48c534dfe73d34408c254c3af/merged
overlay        overlay    28G   22G  6.2G  78% /var/lib/docker/overlay2/7e0ddc26d989c35fa1115b07a552bc882857e54b6876bedbd1ba4cd4066fba31/merged
overlay        overlay    28G   22G  6.2G  78% /var/lib/docker/overlay2/18b39941362f777aadadbeb0ccc9235469239c52ceb841065ab301c819fbe0ec/merged
overlay        overlay    28G   22G  6.2G  78% /var/lib/docker/overlay2/31304cc1dcb8844317c6d84f67c4a16231cb7566470128cd364e3e9b56a0ba74/merged
overlay        overlay    28G   22G  6.2G  78% /var/lib/docker/overlay2/40a7f85c913ee8cd7840a566d4082fe29db2d06bbac1a676e10cab39cc03395c/merged
overlay        overlay    28G   22G  6.2G  78% /var/lib/docker/overlay2/203339b29f19de43ae19dc9acafc9f3a4efea8e084b8b077a107d1e4c3cc8ab3/merged
overlay        overlay    28G   22G  6.2G  78% /var/lib/docker/overlay2/3972601076a8d3ed3d98ae705a6d09f7350f8c698d1b52402cd369b838b9c413/merged
overlay        overlay    28G   22G  6.2G  78% /var/lib/docker/overlay2/62a370c50dea32f9d5e6d834db76b85e8bb2af669a589e7be55bbe4df199e0c1/merged

Time taken to generate the "log" and "log.tmpfs" folder in archive
[ TAR /var/log Files ] : 83928 msec

File count at original log file location
find $path -type f | wc -l
root@sonic:/tmp/tar# find $path -type f | wc -l
5
root@sonic:/tmp/tar# 

File count at extracted tar file location
find . -type f | wc -l
root@sonic:/tmp/tar/sonic_dump_sonic_20230913_060713/log.tmpfs# find . -type f | wc -l
5
```

### CODE REVIEW

**Review by prgeor — APPROVED** [review]

**Comment by prgeor** [comment]
@mihirpat1 please check the build failure

**Comment by mihirpat1** [comment]
> @mihirpat1 please check the build failure

Sure, I have re-run it now since the failure was due to a baseline issue (https://github.com/sonic-net/sonic-host-services/pull/74).

**Comment by mihirpat1** [comment]
@yxieca - It will be great if you can help in merging this to 202205
@StormLiangMS - It will be great if you can help in merging this to 202211 and 202305
@qiluo-msft - It will be great if you can help in merging this to 202012

ADO - 25129114

**Comment by liuh-80** [comment]
@mihirpat1 , this PR has conflict when cherry-pick  to 202012, please create manual cherry-pick PR.

**Pull request merged**
