### PR TITLE
Add CLI command for ECMP calculator

### PR DESCRIPTION
**Pull request by liorghub**
#### What I did
I have added a new CLI command for calling ECMP calculator.

#### How I did it
Add new CLI command. Command handler calls script /usr/bin/ecmp_calc.py

#### How to verify it
Call command and verify its output.
#### New command output (if the output of a command-line utility has changed)
```
root@sonic:/home/admin# show ip ecmp-egress-port --ingress-port Ethernet64 --packet /tmp/packet.json
Egress port: Ethernet0
root@sonic:/home/admin# 
```

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@prsunny could you please review or suggest someone who can?

**Review by liat-grozovik — CHANGES_REQUESTED** [review]
missing tests for new code. please add
missing changes in command reference guide. please add

**Comment by prsunny** [comment]
This is a vendor specific utility. I thought we can directly use the utility to get the hash result. I don't think we need to expose it via a generic CLI command.

**Comment by liat-grozovik** [comment]
> 

In this case, the utility is already available and readme file explain directly how it can be used.
I was under the impression you would like to have the CLI and if the utility available it will be running.
But if this is not required, we can close this PR and leave with the utility itself.

**Pull request closed without merging**
