### PR TITLE
Fix sfputil CLI failure for multi-asic platforms

### PR DESCRIPTION
**Pull request by longhuan-cisco**
#### What I did
This PR is to fix issue https://github.com/sonic-net/sonic-utilities/issues/3167

Basically sfputil Cli became broken on multi-asic platforms after introduction of https://github.com/sonic-net/sonic-buildimage/pull/10960 which removed the initialization of global DB config from portconfig.py (library side) and expects application to do it, but here application side (sfputil) was not updated accordingly. 

#### How I did it
Add load_db_config call to sfputil for initialization

#### How to verify it
Before fix:
```
root@sonic:/home# sfputil show presence                                                                                                                                                                                     
Error reading port info (:- validateNamespace: Initialize global DB config using API SonicDBConfig::initializeGlobalConfig)                                                                                                       
```

After fix:
```
root@sonic:/home# sfputil show presence
Port         Presence                                   
-----------  -----------                                
Ethernet0    Present                                    
Ethernet4    Not present                                
Ethernet8    Present                                    
Ethernet12   Present                                    
Ethernet16   Not present       
...
```

### CODE REVIEW

**Comment by longhuan-cisco** [comment]
@prgeor @abdosi @SuvarnaMeenakshi @bmridul 
Please take a look, thanks

**Review by SuvarnaMeenakshi — DISMISSED** [review]
lgtm

**Review by abdosi — DISMISSED** [review]

**Review by prgeor — DISMISSED** [review]

**Comment by prgeor** [comment]
> @prgeor @abdosi @SuvarnaMeenakshi @bmridul Please take a look, thanks

@longhuan-cisco please test this on NON-multi asic platform

**Comment by longhuan-cisco** [comment]
> @longhuan-cisco please test this on NON-multi asic platform

@prgeor Verified on non-multi-asic platforms also: 
```
root@sonic:/home# ls /run/redis/sonic-db/
database_config.json
root@sonic:/home# sfputil show presence
Port         Presence
-----------  -----------
Ethernet0    Present
Ethernet8    Present
Ethernet16   Present
Ethernet24   Present
Ethernet32   Present
...
```

**Comment by longhuan-cisco** [comment]
> @longhuan-cisco please check the code coverage

@prgeor addressed it.

**Review by SuvarnaMeenakshi — APPROVED** [review]

**Pull request merged**
