### PR TITLE
[vlan] Refresh dhcpv6_relay config while adding/deleting a vlan

### PR DESCRIPTION
**Pull request by yaqiangz**
#### What I did
Currently, add/del a vlan doesn't change related dhcpv6_relay config, which is incorrect.

#### How I did it
1. Add dhcp_relay table init entry while adding vlan
2. Delete dhcp_relay related config while deleting vlan
3. Add unitest

#### How to verify it
1. By unitest
```
===================================================================================================================== test session starts ======================================================================================================================
platform linux -- Python 3.9.2, pytest-6.0.2, py-1.10.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /sonic/src/sonic-utilities, configfile: pytest.ini
plugins: pyfakefs-5.0.0, cov-2.10.1
collected 2171 items  

tests/vlan_test.py::TestVlan::test_show_vlan PASSED                                                                                                                                                                                                      [ 71%]
tests/vlan_test.py::TestVlan::test_show_vlan_brief PASSED                                                                                                                                                                                                [ 72%]
tests/vlan_test.py::TestVlan::test_show_vlan_brief_verbose PASSED                                                                                                                                                                                        [ 72%]
tests/vlan_test.py::TestVlan::test_show_vlan_brief_in_alias_mode PASSED                                                                                                                                                                                  [ 72%]
tests/vlan_test.py::TestVlan::test_show_vlan_brief_explicit_proxy_arp_disable PASSED                                                                                                                                                                     [ 72%]
tests/vlan_test.py::TestVlan::test_show_vlan_config PASSED                                                                                                                                                                                               [ 72%]
tests/vlan_test.py::TestVlan::test_show_vlan_config_in_alias_mode PASSED                                                                                                                                                                                 [ 72%]
tests/vlan_test.py::TestVlan::test_config_vlan_add_vlan_with_invalid_vlanid PASSED                                                                                                                                                                       [ 72%]
tests/vlan_test.py::TestVlan::test_config_vlan_add_vlan_with_exist_vlanid PASSED                                                                                                                                                                         [ 72%]
tests/vlan_test.py::TestVlan::test_config_vlan_del_vlan_with_invalid_vlanid PASSED                                                                                                                                                                       [ 72%]
tests/vlan_test.py::TestVlan::test_config_vlan_del_vlan_with_nonexist_vlanid PASSED                                                                                                                                                                      [ 72%]
tests/vlan_test.py::TestVlan::test_config_vlan_add_member_with_invalid_vlanid PASSED                                                                                                                                                                     [ 72%]
tests/vlan_test.py::TestVlan::test_config_vlan_add_member_with_nonexist_vlanid PASSED                                                                                                                                                                    [ 72%]
tests/vlan_test.py::TestVlan::test_config_vlan_add_exist_port_member PASSED                                                                                                                                                                              [ 72%]
tests/vlan_test.py::TestVlan::test_config_vlan_add_nonexist_port_member PASSED                                                                                                                                                                           [ 72%]
tests/vlan_test.py::TestVlan::test_config_vlan_add_nonexist_portchannel_member PASSED                                                                                                                                                                    [ 72%]
tests/vlan_test.py::TestVlan::test_config_vlan_add_portchannel_member PASSED                                                                                                                                                                             [ 72%]
tests/vlan_test.py::TestVlan::test_config_vlan_add_rif_portchannel_member PASSED                                                                                                                                                                         [ 72%]
tests/vlan_test.py::TestVlan::test_config_vlan_with_vxlanmap_del_vlan PASSED                                                                                                                                                                             [ 72%]
tests/vlan_test.py::TestVlan::test_config_vlan_del_vlan PASSED                                                                                                                                                                                           [ 72%]
tests/vlan_test.py::TestVlan::test_config_vlan_del_nonexist_vlan_member PASSED                                                                                                                                                                           [ 72%]
tests/vlan_test.py::TestVlan::test_config_add_del_vlan_and_vlan_member PASSED                                                                                                                                                                            [ 72%]
tests/vlan_test.py::TestVlan::test_config_add_del_vlan_and_vlan_member_in_alias_mode PASSED                                                                                                                                                              [ 73%]
tests/vlan_test.py::TestVlan::test_config_vlan_proxy_arp_with_nonexist_vlan_intf_table PASSED                                                                                                                                                            [ 73%]
tests/vlan_test.py::TestVlan::test_config_vlan_proxy_arp_with_nonexist_vlan_intf PASSED                                                                                                                                                                  [ 73%]
tests/vlan_test.py::TestVlan::test_config_vlan_proxy_arp_enable PASSED                                                                                                                                                                                   [ 73%]
tests/vlan_test.py::TestVlan::test_config_vlan_proxy_arp_disable PASSED                                                                                                                                                                                  [ 73%]
tests/vlan_test.py::TestVlan::test_config_2_untagged_vlan_on_same_interface PASSED                                                                                                                                                                       [ 73%]
tests/vlan_test.py::TestVlan::test_config_set_router_port_on_member_interface PASSED                                                                                                                                                                     [ 73%]
tests/vlan_test.py::TestVlan::test_config_vlan_add_member_of_portchannel PASSED                                                                                                                                                                          [ 73%]
tests/vlan_test.py::TestVlan::test_config_add_del_vlan_dhcp_relay[ipv4] PASSED                                                                                                                                                                           [ 73%]
tests/vlan_test.py::TestVlan::test_config_add_del_vlan_dhcp_relay[ipv6] PASSED                                                                                                                                                                           [ 73%]


----------- coverage: platform linux, python 3.9.2-final-0 -----------
Name                                                Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------------------------------------
utilities_common/dhcp_relay_util.py                    15      2      2      1    82%
-------------------------------------------------------------------------------------
TOTAL                                               39535  11393  14040   2014    68%
```
2. install whl and run cli
```
admin@bjw-can-720dt-2:~$ sonic-db-cli CONFIG_DB hgetall "DHCP_RELAY|Vlan1001"
{}
admin@bjw-can-720dt-2:~$ sudo config vlan add 1001
admin@bjw-can-720dt-2:~$ sonic-db-cli CONFIG_DB hgetall "DHCP_RELAY|Vlan1001"
{'vlanid': '1001'}
admin@bjw-can-720dt-2:~$ sudo config vlan del 1001
Restarting DHCP relay service...
admin@bjw-can-720dt-2:~$ sonic-db-cli CONFIG_DB hgetall "DHCP_RELAY|Vlan1001"
{}
```

### CODE REVIEW

**Comment by yaqiangz** [comment]
@kellyyeh @Blueve @jcaiMR Could you please help to review this PR

**Review by jcaiMR — COMMENTED** [review]
Have you tried dhcp related test cases. Not Sure if there any case that would have some config sequence. Like first insert dhcp relay config, then bring up vlan.

**Comment by yaqiangz** [comment]
> Have you tried dhcp related test cases. Not Sure if there any case that would have some config sequence. Like first insert dhcp relay config, then bring up vlan.

@jcaiMR Added unitest `test_config_add_exist_vlan_dhcp_relay` to cover. Also added restart dhcp_relay while adding vlan to support del dhcp6 config without restart dhcp_relay and then add vlan

**Review by jcaiMR — APPROVED** [review]

**Comment by vadymhlushko-mlnx** [comment]
@yaqiangz hi! It seems like, because of this PR the [submodule update PR](https://github.com/sonic-net/sonic-buildimage/pull/13790) tests failing, could you please take a look at - [failed tests log](https://www.testbed-tools.org/scheduler/testplan/63ea585de429c1efea2d7264)

**Comment by vadymhlushko-mlnx** [comment]
Hi @yaqiangz. It seems like because of this PR the [submodule update PR](https://github.com/sonic-net/sonic-buildimage/pull/13790) tests are failing. Could you please take a look at - [test failures](https://www.testbed-tools.org/scheduler/testplan/63ea585de429c1efea2d7264)?

**Comment by yaqiangz** [comment]
> Hi @yaqiangz. It seems like because of this PR the [submodule update PR](https://github.com/sonic-net/sonic-buildimage/pull/13790) tests are failing. Could you please take a look at - [test failures](https://www.testbed-tools.org/scheduler/testplan/63ea585de429c1efea2d7264)?

Hi @vadymhlushko-mlnx, sorry for the inconvenience. I am working on fix it. And have created issue to trace https://github.com/sonic-net/sonic-utilities/issues/2677

**Comment by liat-grozovik** [comment]
@yaqiangz as this is holding submodule update, should we consider reverting it and then adding it back when the fix is avaialble?

**Comment by yaqiangz** [comment]
> @yaqiangz as this is holding submodule update, should we consider reverting it and then adding it back when the fix is avaialble?

@liat-grozovik https://github.com/sonic-net/sonic-utilities/pull/2678 https://github.com/sonic-net/sonic-buildimage/pull/13822 have created fix PR, if nothing unexpected. It would be resolved after a few hours. (Fix in sonic-utilities should be merged after fix in sonic-buildimage is merged)

**Comment by yaqiangz** [comment]
> > @yaqiangz as this is holding submodule update, should we consider reverting it and then adding it back when the fix is avaialble?
> 
> @liat-grozovik #2678 [sonic-net/sonic-buildimage#13822](https://github.com/sonic-net/sonic-buildimage/pull/13822) have created fix PR, if nothing unexpected. It would be resolved after a few hours. (Fix in sonic-utilities must be merged after fix in sonic-buildimage is merged) I hope to wait the fix done. But if submodule update is urgent, we can do reverting

@liat-grozovik @vadymhlushko-mlnx Fix has been merged

**Pull request merged**
