### PR TITLE
[Marvell] platform renaming for innovium

### PR DESCRIPTION
**Pull request by krismarvell**
#### What I did
platform renaming for marvell teralynx platform.

#### How I did it
innovium asictype checks are renamed to marvell-teralynx

#### How to verify it
run generate_dump script with the changes in both platforms and verified the outputs remains the same

#### Previous command output (if the output of a command-line utility has changed)
NA

#### New command output (if the output of a command-line utility has changed)
NA

### CODE REVIEW

**Comment by krismarvell** [comment]
@saiarcot895 @qiluo-msft Can you pls help review

**Review by saiarcot895 — APPROVED** [review]

**Pull request merged**
