### PR TITLE
[config db] Trim garbage charactor in "DEVICE_METADATA" of config db

### PR DESCRIPTION
**Pull request by wenyiz2021**
This is to prevent a user error in ADO: 28004860
where there was an extra "\n" at the end of mac, in "DEVICE_METADATA" section.

image

#### What I did
1. the garbage char could be generated with "load_minigraph" if '-override-config' is specified, and if golden_config has garbage char.
2. it could also be introduced by "config reload"
#### How I did it
in both cases, add the strip method for "mac" as well as "platform" whenever the DEVICE_METADATA tends to be modified. to trim the extra "\n"
#### How to verify it
1. add an extra "\n" at end of mac, in config db
2. did config reload, garbage char exists
3. apply changes in this PR

### CODE REVIEW

**Comment by bingwang-ms** [comment]
The changes look good to me. Can you also add some test to cover the change?

**Comment by wenyiz2021** [comment]
> The changes look good to me. Can you also add some test to cover the change?

hi @bingwang-ms , this change is already covered by tests/config_override_test.py::TestConfigOverrideMultiasic::test_device_metadata_gen_sysinfo

https://dev.azure.com/mssonic/build/_build/results?buildId=718282&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=4db68653-cc6c-5898-0eb1-3562ebc9ad55

**Review by bingwang-ms — APPROVED** [review]

**Comment by wenyiz2021** [comment]
@bingwang-ms could you approve again? thanks!

**Review by bingwang-ms — APPROVED** [review]

**Comment by bingwang-ms** [comment]
Readding label for cherry-pick

**Pull request merged**
