### PR TITLE
[master][chassis][show-runningconfig] Fix the show runningconfiguration all issue on the Supervisor

### PR DESCRIPTION
**Pull request by mlok-nokia**
#### What I did
bgp is not supported on Supervisor card,  "show runningconfiguration all" fails on the Supervisor since the bgp services is disable. Add code to check if bgp state in the FEATURE table is able before it tries to get the BGP configuration to avoid the error. Fix issue https://github.com/sonic-net/sonic-buildimage/issues/18276
#### How I did it
Since BGP feature state is disabled in the FEATURE table on Supervisor card, add method is_bgp_feature_state_enabled() to the bgp_util.py check the BGP feature state.  Modify the "show runningconfiguration all" to call the is_bgp_feature_state_enabled(), then call the run_ngp_show _command to get the bgp configuration.

#### How to verify it
1) Execute the "show runningconfiguration all" command on Supervisor. The following output should be shown without any error.
```
admin@ixre-cpm-chassis15:~$ show runningconfiguration all | more
{
    "localhost": {
        "AUTO_TECHSUPPORT": {
            "GLOBAL": {
                "available_mem_threshold": "10.0",
                "max_core_limit": "5.0",
                "max_techsupport_limit": "10.0",
                "min_available_mem": "200",
                "rate_limit_interval": "180",
                "since": "2 days ago",
                "state": "enabled"
            }
        },
        "AUTO_TECHSUPPORT_FEATURE": {
            "bgp": {
                "available_mem_threshold": "10.0",
                "rate_limit_interval": "600",
                "state": "enabled"
            },
            "database": {
                "available_mem_threshold": "10.0",
                "rate_limit_interval": "600",
                "state": "enabled"
            },
            "dhcp_relay": {
                "available_mem_threshold": "10.0",
                "rate_limit_interval": "600",
                "state": "enabled"
            },
            "eventd": {
                "available_mem_threshold": "10.0",
                "rate_limit_interval": "600",
                "state": "enabled"
            },
            "gnmi": {
                "available_mem_threshold": "10.0",
                "rate_limit_interval": "600",
                "state": "enabled"
            },
            "lldp": {
                "available_mem_threshold": "10.0",
                "rate_limit_interval": "600",
                "state": "enabled"
            },
....
    },
    "asic0": {
        "AUTO_TECHSUPPORT": {
            "GLOBAL": {
                "available_mem_threshold": "10.0",
                "max_core_limit": "5.0",
                "max_techsupport_limit": "10.0",
                "min_available_mem": "200",
                "rate_limit_interval": "180",
                "since": "2 days ago",
                "state": "enabled"
            }
        },
        "AUTO_TECHSUPPORT_FEATURE": {
            "bgp": {
                "available_mem_threshold": "10.0",
                "rate_limit_interval": "600",
                "state": "enabled"
            },
            "database": {
                "available_mem_threshold": "10.0",
                "rate_limit_interval": "600",
                "state": "enabled"
            },
    "asic1": {
        "AUTO_TECHSUPPORT": {
            "GLOBAL": {
                "available_mem_threshold": "10.0",
                "max_core_limit": "5.0",
                "max_techsupport_limit": "10.0",
                "min_available_mem": "200",
                "rate_limit_interval": "180",
                "since": "2 days ago",
                "state": "enabled"
            }
        },
        "AUTO_TECHSUPPORT_FEATURE": {
            "bgp": {
                "available_mem_threshold": "10.0",
                "rate_limit_interval": "600",
                "state": "enabled"
            },
            "database": {
                "available_mem_threshold": "10.0",
                "rate_limit_interval": "600",
                "state": "enabled"
            },
            "dhcp_relay": {
                "available_mem_threshold": "10.0",
...
...
    }
}

```

### CODE REVIEW

**Comment by mlok-nokia** [comment]
@rlhui @judyjoseph Please review this PR for master branch.

**Review by wen587 — APPROVED** [review]
lgtm

**Review by judyjoseph — COMMENTED** [review]
lgtm

**Review by judyjoseph — APPROVED** [review]

**Comment by wen587** [comment]
@gechiang This PR has a bug fix and need to be backported to 202205 chassis

**Comment by gechiang** [comment]
> @gechiang This PR has a bug fix and need to be backported to 202205 chassis

@wen587 , 
Please help review this PR:
https://github.com/sonic-net/sonic-utilities.msft/pull/76
which port this PR to the MSFT repo 202205 branch.

**Comment by gechiang** [comment]
MSFT ADO: 28384064

**Pull request merged**
