### PR TITLE
Added support for Voq Counters(SAI_SWITCH_STAT_PACKET_INTEGRITY_DROP,SAI_QUEUE_STAT_CREDIT_WD_DELETED_PACKETS) for Voq/Fabric switches

### PR DESCRIPTION
**Pull request by saksarav-nokia**
#### What I did
 Added cli support to show SAI_SWITCH_STAT_PACKET_INTEGRITY_DROP counter in show dropcounter counts command and show SAI_QUEUE_STAT_CREDIT_WD_DELETED_PACKETS counters in show queue counter --voq command.

#### How I did it
     Modified the dropstat and queuestat cli commands to show these new counters 
#### How to verify it
   Simulated the Packet integrity (CRC, RQP errors) and Credit Watchdog delete drops (disabled the TX for the ports and simulated the credit watchdog deletes) and verified that the show commands are showing the correct output from COUNTERS_DB.
#### New command output (if the output of a command-line utility has changed)
1)show dropcounter counts
2)show queue counter --voq

### CODE REVIEW

**Comment by saksarav-nokia** [comment]
@rlhui , please review it

**Comment by saksarav-nokia** [comment]
https://github.com/sonic-net/sonic-swss/pull/3152 has the corresponding orchagent changes.

**Comment by vmittal-msft** [comment]
@saksarav-nokia  Can you please share o/p for both commands ?

**Comment by vmittal-msft** [comment]
Also, we may need to check on T0/T1 to make sure these changes don't break anything there.

**Review by vmittal-msft — COMMENTED** [review]
Commented above

**Comment by saksarav-nokia** [comment]
Vineet, Here is the output of the show commands
admin@ixre-egl-board29:~$ sudo ip netns exec asic0 show queue counters --voq
                       Port    Voq    Counter/pkts    Counter/bytes    Drop/pkts    Drop/bytes    Credit-WD-Del/pkts
---------------------------  -----  --------------  ---------------  -----------  ------------  --------------------
ixre-egl-board29|asic0|Cpu0   VOQ0               6              720            0             0                     0
ixre-egl-board29|asic0|Cpu0   VOQ1               0                0            0             0                     0
ixre-egl-board29|asic0|Cpu0   VOQ2               0                0            0             0                     0
ixre-egl-board29|asic0|Cpu0   VOQ3               0                0            0             0                     0
ixre-egl-board29|asic0|Cpu0   VOQ4            1027           194875            0             0                     0
ixre-egl-board29|asic0|Cpu0   VOQ5               0                0            0             0                     0
ixre-egl-board29|asic0|Cpu0   VOQ6               0                0            0             0                     0
ixre-egl-board29|asic0|Cpu0   VOQ7               0                0            0             0                     0

                            Port    Voq    Counter/pkts    Counter/bytes    Drop/pkts    Drop/bytes    Credit-WD-Del/pkts
--------------------------------  -----  --------------  ---------------  -----------  ------------  --------------------
ixre-egl-board29|asic0|Ethernet0   VOQ0               0                0            0             0                     0
ixre-egl-board29|asic0|Ethernet0   VOQ1               0                0            0             0                     0
ixre-egl-board29|asic0|Ethernet0   VOQ2               0                0            0             0                     0
ixre-egl-board29|asic0|Ethernet0   VOQ3               0                0            0             0                     5
ixre-egl-board29|asic0|Ethernet0   VOQ4               0                0            0             0                     0
ixre-egl-board29|asic0|Ethernet0   VOQ5               0                0            0             0                     0
ixre-egl-board29|asic0|Ethernet0   VOQ6               0                0            0             0                     0
ixre-egl-board29|asic0|Ethernet0   VOQ7               0                0            0             0                     0


admin@ixre-egl-board29:~$ sudo ip netns exec asic1 show dropcounters counts
SWITCH LEVEL COUNTERS:
  SWITCH-ID    PKT_INTEGRITY_ERR
-----------  -------------------
          2                   4

        IFACE    STATE    RX_ERR    RX_DROPS    TX_ERR    TX_DROPS
-------------  -------  --------  ----------  --------  ----------
    Ethernet0        X         0           0         0           0
    Ethernet8        X         0           0         0           0
   Ethernet16        X         0           0         0           0
   Ethernet24        X         0           0         0           0
   Ethernet32        X         0           0         0           0
   Ethernet40        X         0           0         0           0
   Ethernet48        U         0           5         0           0
   Ethernet56        X         0           0         0           0
   Ethernet64        X         0           0         0           0
   Ethernet72        X         0           0         0           0
   Ethernet80        U         0           0         0           0
   Ethernet88        X         0           0         0           0
   Ethernet96        X         0           0         0           0
  Ethernet104        X         0           0         0           0
  Ethernet112        U         0           1         0           0
  Ethernet120        X         0           0         0           0
  Ethernet128        X         0           0         0           0
  Ethernet136        X         0           0         0           0
 Ethernet-IB0        U         0           0         0           0
Ethernet-Rec0        U         0           0         0           0

**Comment by saksarav-nokia** [comment]
> Also, we may need to check on T0/T1 to make sure these changes don't break anything there.



> Also, we may need to check on T0/T1 to make sure these changes don't break anything there.

I will add a check for switch_type as fabric or voq.

**Comment by saksarav-nokia** [comment]
image

**Comment by saksarav-nokia** [comment]
image

**Comment by saksarav-nokia** [comment]
image

**Comment by vmittal-msft** [comment]
> drop counters with packet integrity counters in IMM image

@saksarav-nokia Can you please change to name of switch type to VoQ

**Comment by vmittal-msft** [comment]
> > drop counters with packet integrity counters in IMM image
> 
> @saksarav-nokia Can you please change to name of switch type to VoQ

or may be we can remove first 2 lines - switch type and switch level

**Comment by saksarav-nokia** [comment]
> > > drop counters with packet integrity counters in IMM image
> > 
> > 
> > @saksarav-nokia Can you please change to name of switch type to VoQ
> 
> or may be we can remove first 2 lines - switch type and switch level

switch type is already removed. Don't you think having switch level helps the user?

**Comment by vmittal-msft** [comment]
please add heading as "switch counters" and "interface counters".

**Review by vmittal-msft — APPROVED** [review]

**Pull request merged**
