### PR TITLE
portstat overflow: Convert to float first from exponent notation before input to int()

### LINKED ISSUE #3419: portstat gives traceback when the counters exceed 10^14
#### Description
When the interface counters exceed 10^14, the portstat utility gives traceback. So the "show interface counter" gives the traceback.

`root@yy39top-lc4:/home/cisco# sonic-clear counter
Traceback (most recent call last):
  File "/usr/local/bin/portstat", line 675, in <module>
    main()
  File "/usr/local/bin/portstat", line 635, in main
    cnstat_dict, ratestat_dict = portstat.get_cnstat_dict()
  File "/usr/local/bin/portstat", line 151, in get_cnstat_dict
    self.collect_stat()
  File "/usr/local/lib/python3.9/dist-packages/utilities_common/multi_asic.py", line 157, in wrapped_run_on_all_asics
    func(self,  *args, **kwargs)
  File "/usr/local/bin/portstat", line 161, in collect_stat
    cnstat_dict, ratestat_dict = self.get_cnstat()
  File "/usr/local/bin/portstat", line 215, in get_cnstat
    cnstat_dict[port] = get_counters(port)
  File "/usr/local/bin/portstat", line 182, in get_counters
    fields[pos] = str(int(fields[pos]) + int(fvs[counter_name]))
ValueError: invalid literal for int() with base 10: '1.5530548686308e+14'

root@yy39top-lc4:/home/cisco# `

## Steps to reproduce the issue
1. Run trafffic in the DUT interface enough to raise the counter values to above 10^14.
2. Run any command that reads the counters: "show inter counter", "sonic-clear counter", "portstat"
3. All of them give traceback.

#### Describe the results you received
Pls see the description.

#### Describe the results you expected
We need the output to show the counter values instead of traceback.

#### Output of `show version`

The version of the DUT doesn't seem to matter.

### PR DESCRIPTION
**Pull request by rraghav-cisco**
fixes sonic-net/sonic-buildimage#20407,

#### What I did
Typecast the exponential notation to float before being input to int() function.
#### How to verify it
1. Run traffic on any dataport so that the counters exceed 10^14. 
2. After that run the sonic commands that use use portstat.
#### Previous command output (if the output of a command-line utility has changed)
Traceback was seen, as shown in sonic-net/sonic-buildimage#20407 .

#### New command output (if the output of a command-line utility has changed)
It prints the output correctly:

```
root@yy39top-lc4:/home/cisco# show int count
      IFACE    STATE              RX_OK         RX_BPS    RX_UTIL    RX_ERR           RX_DRP    RX_OVR    TX_OK        TX_BPS    TX_UTIL    TX_ERR    TX_DRP    TX_OVR
-----------  -------  -----------------  -------------  ---------  --------  ---------------  --------  -------  ------------  ---------  --------  --------  --------
  Ethernet0        U  1,405,887,650,456  38113.57 MB/s     76.23%         0               13         0    4,841  2247.54 KB/s      0.00%         0         3         0
  Ethernet8        X                  0       0.00 B/s      0.00%         0                0         0        0      0.00 B/s      0.00%         0         0         0
```

### CODE REVIEW

**Comment by anamehra** [comment]
Hi @abdosi , @cyw233 , please review.

**Comment by cyw233** [comment]
adding @auspham for viz

**Comment by auspham** [comment]
Hi @rraghav-cisco this is the same fix as https://github.com/sonic-net/sonic-utilities/pull/3538/files where @qiluo-msft suspect that this issue happened before. I suspect it happened already while converting counter from SAI apis

**Comment by rraghav-cisco** [comment]
> Hi @rraghav-cisco this is the same fix as https://github.com/sonic-net/sonic-utilities/pull/3538/files where @qiluo-msft suspect that this issue happened before. I suspect it happened already while converting counter from SAI apis

@auspham : Pls close either one of them, as needed.

**Comment by auspham** [comment]
@rraghav-cisco, this will only fix the show utilities command, the scientific notation however will still be there in the database. 
I have updated cisco jira ticket to look into this

Hi @yejianquan, could you please help reviewing this change from CISCO and if we can merge it in to unblock this testcase?

**Comment by arlakshm** [comment]
@auspham please resolve the conflicts

**Comment by anamehra** [comment]
This PR can be closed. Issue is fixed by https://github.com/sonic-net/sonic-utilities/pull/3596

**Pull request closed without merging**
