### PR TITLE
[202311] Support reading/writing module EEPROM data by page and offset (#3008)

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Backport PR to 202311: https://github.com/sonic-net/sonic-utilities/pull/3008

#### What I did

Add two CLIs:

- sfputil read-eeprom
- sfputil write-eeprom

Allow user to read/write EEPROM by page and offset

#### How I did it

See design:
https://github.com/sonic-net/SONiC/pull/1475

#### How to verify it

Unit test

#### New command output (if the output of a command-line utility has changed)

```
sfputil read-eeprom Ethernet0 0 100 2
00000064 4a 44                                            |..|
sfputil read-eeprom Ethernet0 0 0 32
00000000 11 08 06 00 00 00 00 00  00 00 00 00 00 00 00 00 |................|
00000010 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 |................|
sfputil read-eeprom Ethernet0 0 100 2 --no-format
4a44
```

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@prgeor please approve the PR as well

**Comment by liat-grozovik** [comment]
@prgeor can you approve the backport one as well?

**Comment by liat-grozovik** [comment]
@prgeor @keboliu as the original reviewers. can you please review and approve?

**Review by keboliu — APPROVED** [review]

**Comment by keboliu** [comment]
@yxieca @prgeor would you please approve and merge? this is a backport PR.

**Review by prgeor — APPROVED** [review]

**Pull request merged**
