### PR TITLE
route_check.py should not print too many outputs to stdout

### PR DESCRIPTION
**Pull request by MaxXiao12**
Otherwise it fills up the pipe and print() will block. When this happens, `route_check.py` will timeout and eventually killed by `monit` after several minutes.

Request to cast the change to `202305` branch.

#### What I did
Add an option in `print_message()` to skip printing.

#### How I did it
Add an option `write_to_stdout=True`, in `mitigate_installed_not_offloaded_frr_routes()` call `print_message()` with `write_to_stdout=False`.

#### How to verify it
Manually run route_check.py, verify that the messages were shown in syslog but not in stdout.

### CODE REVIEW

**Comment by StormLiangMS** [comment]
@dgsudharsan  @prsunny would you help to review and comment?

**Comment by prsunny** [comment]
Can you please check on coverage? Changes lgtm

**Comment by dgsudharsan** [comment]
Changes LGTM. Please add coverage as requested by Prince

**Comment by MaxXiao12** [comment]
> Can you please check on coverage? Changes lgtm

Hi Prince, I wasn't able to add labels to the PR to indicate status and also which branch to cast to... Could you check if I am included in the right group? I am working on the test in the meantime to close the gap.

Thanks!

**Comment by prsunny** [comment]
@lolyu for viz

**Comment by StormLiangMS** [comment]
> > Can you please check on coverage? Changes lgtm
> 
> Hi Prince, I wasn't able to add labels to the PR to indicate status and also which branch to cast to... Could you check if I am included in the right group? I am working on the test in the meantime to close the gap.
> 
> Thanks!

Hi @MaxXiao12  you can add request in the description of PR. The maintainer or release mgr will add tags.

**Comment by MaxXiao12** [comment]
> > > Can you please check on coverage? Changes lgtm
> > 
> > 
> > Hi Prince, I wasn't able to add labels to the PR to indicate status and also which branch to cast to... Could you check if I am included in the right group? I am working on the test in the meantime to close the gap.
> > Thanks!
> 
> Hi @MaxXiao12 you can add request in the description of PR. The maintainer or release mgr will add tags.

Updated the PR to request for `202305` branch

**Review by lolyu — APPROVED** [review]

**Review by prsunny — APPROVED** [review]

**Pull request merged**
