### PR TITLE
[generate_dump]: Enhance show techsupport for cisco-8000 platform

### PR DESCRIPTION
**Pull request by gvlaemyn**
Signed-off-by: Geert Vlaemynck <gvlaemyn@cisco.com>

#### What I did
Added cisco-8000 specific platform information to "show techsupport" tarfile

#### How I did it
Added collect_cisco_8000 function to scripts/generate_dump which filters out the wanted files from /usr/share/sonic/device/${platform} and saves them in the techsupport tarfile under sai subdirectory

#### How to verify it
Run "show techsupport" and grep sai in the generated techsupport tarfile

### CODE REVIEW

**Comment by yxieca** [comment]
@gvlaemyn please add unit test.

**Comment by alpeshspatel** [comment]
Hi @yxieca  I have opened https://github.com/sonic-net/sonic-utilities/issues/2432 for this. 

I cannot assign the issue to Geert. 
Can you please do the needful on the current issue and merge in master when possible.

**Comment by alpeshspatel** [comment]
@yxieca can you merge this PR in master? Geert will tackle the unit-test via the separate issue.

**Comment by alpeshspatel** [comment]
@yxieca Is this PR not merged in 202205 yet?

**Comment by yxieca** [comment]
> @yxieca Is this PR not merged in 202205 yet?

@alpeshspatel , No. I cannot cherry-pick this change cleanly. Can you or @gvlaemyn create an PR for 202205 branch?

**Comment by alpeshspatel** [comment]
sure @yxieca , either @gvlaemyn  or I will do that and reach out to you.

**Pull request merged**
