### PR TITLE
Fix bug with checking VRF's routes in route_check.py 

### PR DESCRIPTION
**Pull request by bratashX**
Signed-off-by: Petro Bratash <petrox.bratash@intel.com>

#### What I did
Add capability to check routes with VRF

#### How I did it
All routes in VRF have a specific prefix in name.

**_Route table when we have VRF:_**
```
admin@igk-5-dut:~$ redis-cli -n 0 keys "ROUTE_TABLE*" 
    1) "ROUTE_TABLE:Vrf2:20c0:cb50:0:80::/64"
    2) "ROUTE_TABLE:Vrf2:192.211.48.0/25"
    3) "ROUTE_TABLE:Vrf1:192.246.8.128/25"
    4) "ROUTE_TABLE:Vrf1:192.222.8.0/25"
    5) "ROUTE_TABLE:Vrf2:192.246.64.0/25"
    .......
```

**_Route table without VRF:_**
```
admin@cab18-2-dut:~$ redis-cli -n 0 keys "ROUTE_TABLE*"
1) "ROUTE_TABLE:192.168.0.0/21"
2) "ROUTE_TABLE:10.1.0.32"
3) "ROUTE_TABLE:fc02:1000::/64"
4) "ROUTE_TABLE:fe80::/64"
5) "ROUTE_TABLE:fc00:1::32"
.......
```
Remove **_Vrf_** prefix from route. Without Vrf, we can compare routes from APP and ASIC DB.

#### How to verify it
Run next command on SONiC:
1. `sudo config vrf add Vrf1`
2. `sudo config interface vrf bind PortChannel101 Vrf1`
3. `sudo config interface ip add PortChannel101 10.0.0.56/31`
4. `/usr/local/bin/route_check.py`

Also can run SONiC TC  `vrf/test_vrf.py::TestVrfDeletion::test_vrf1_neigh_after_restore` and check syslog 

#### Previous command output (if the output of a command-line utility has changed)
```
$ /usr/local/bin/route_check.py
Failure results: {{
    "Unaccounted_ROUTE_ENTRY_TABLE_entries": [
        "10.0.0.56/31"
    ]
}}
Failed. Look at reported mismatches above
add: []
del: []
```

### CODE REVIEW

**Comment by prsunny** [comment]
What is the fix? We already have the check without VRF. Can you explain a bit more?

**Comment by bratashX** [comment]
> What is the fix? We already have the check without VRF. Can you explain a bit more?

Previously, we skip routes with VRF prefix (ROUTE_TABLE from APP_DB): https://github.com/sonic-net/sonic-utilities/blob/be1866fd3f9d2555c4036e9f1a9b820ae6d5c889/scripts/route_check.py#L284

But from **_ASIC_DB_** we read all routes (including routes from VRF)  and have a problem with comparing.

**Comment by bratashX** [comment]
> > > What is the fix? We already have the check without VRF. Can you explain a bit more?
> > 
> > 
> > Previously, we skip routes with VRF prefix (ROUTE_TABLE from APP_DB):
> > https://github.com/sonic-net/sonic-utilities/blob/be1866fd3f9d2555c4036e9f1a9b820ae6d5c889/scripts/route_check.py#L284
> > 
> > But from **_ASIC_DB_** we read all routes (including routes from VRF) and have a problem with comparing.
> 
> ok, in that case i suggest lets fix the proper way. For VRF routes, lets get the VRF ID from ASIC_DB and compare only routes from that VRF.

We can't compare only routes from specific VRF separatelly because:

- on **APP_DB** used name of VRF (_VRF1, VRF2..etc._) 
 Example route entry from **APP_DB**:
 `"ROUTE_TABLE:Vrf1:10.0.0.56/31"`

- on **ASIC_DB** used virtual router oid 
 Example route entry from **ASIC_DB**:
 `ASIC_STATE:SAI_OBJECT_TYPE_ROUTE_ENTRY:{"dest":"10.0.0.56/31","switch_id":"oid:0x21000000000000","vr":"oid:0x30000000003e3"}`
 
Mapping **_VRF names_** with _**OIDs**_ is absent in REDIS (it's saved into swss code).
 
 In my implementation, I compare all routes from **APP_DB** (without VRF + VRF routes) with all routes from **ASIC_DB**.

**Comment by bratashX** [comment]
@prsunny Could you please take a look?

**Review by prsunny — APPROVED** [review]

**Pull request merged**
