### PR TITLE
Delete .DS_Store

### PR DESCRIPTION
**Pull request by anilkpan**
Delete .DS_Store file that was created by mistake.

### CODE REVIEW

**Review by Blueve — APPROVED** [review]

**Comment by Blueve** [comment]
@anilkpandey  please sign the EasyCLA doc as IC, then we can merge this PR

**Comment by anilkpan** [comment]
@Blueve , I have signed the EasyCLA. Not sure why the check is still failing.

**Comment by Blueve** [comment]
> @Blueve , I have signed the EasyCLA. Not sure why the check is still failing.

@anilkpan  your commit is belong to another account: https://github.com/anilkpandey  maybe you can try sign it using that account?

**Comment by anilkpandey** [comment]
retest this please

**Comment by anilkpandey** [comment]
Done.

**Pull request merged**
