### PR TITLE
[Vxlanmgrd] [CPA] Update the vxlan_tunnel name len to be under IFNAMIZ to overcome netdev creation failure

### PR DESCRIPTION
**Pull request by vivekrnv**
Signed-off-by: Vivek Reddy Karri <vkarri@nvidia.com>

#### Why I did

Fixes https://github.com/sonic-net/sonic-buildimage/issues/10466

```
2022-09-23.02:07:06.587735|VXLAN_TUNNEL_TABLE:neighbor_advertiser|SET|dst_ip:192.168.8.1|src_ip:10.1.0.32
2022-09-23.02:07:06.592107|VXLAN_TUNNEL_MAP_TABLE:neighbor_advertiser:map_1|SET|vlan:Vlan1000|vni:1000
2022-09-23.02:07:06.636334|MIRROR_SESSION|neighbor_advertiser|SET|dst_ip:192.168.8.1|src_ip:10.1.0.32
2022-09-23.02:07:09.609096|ACL_RULE|EVERFLOW|rule_arp|SET|PRIORITY:8888|ether_type:2054|mirror_action:neighbor_advertiser
2022-09-23.02:07:09.647727|ACL_RULE|EVERFLOWV6|rule_nd|SET|ICMPV6_TYPE:135|PRIORITY:8887|mirror_action:neighbor_advertiser
```

```
Sep 21 22:31:19.611617 mtbc-sonic-03-2700 INFO swss#vxlanmgrd: :- doVxlanTunnelMapCreateTask: Create vxlan tunnel map neighbor_advertiser:map_1
Sep 21 22:31:19.613054 mtbc-sonic-03-2700 INFO swss#vxlanmgrd: :- createAppDBTunnelMapTable: App Tunnel Map Table create neighbor_advertiser:map_1
Sep 21 22:31:19.614191 mtbc-sonic-03-2700 INFO swss#vxlanmgrd: :- createVxlanNetdevice: Kernel tnl_name: neighbor_advertiser vni_id: 1000 src_ip: 10.1.0.32 dst_ip:192.168.8.1 vlan_id: 1000
Sep 21 22:31:19.614362 mtbc-sonic-03-2700 INFO swss#vxlanmgrd: :- createVxlanNetdevice: Creating VxlanNetDevice neighbor_advertiser-1000
Sep 21 22:31:19.620672 mtbc-sonic-03-2700 INFO swss#supervisord: vxlanmgrd Error: Attribute failed policy validation
Sep 21 22:31:19.620923 mtbc-sonic-03-2700 INFO swss#supervisord: vxlanmgrd .
Sep 21 22:31:19.626280 mtbc-sonic-03-2700 WARNING swss#vxlanmgrd: :- doVxlanTunnelMapCreateTask: Vxlan Net Dev creation failure for neighbor_advertiser VNI(1000) VLAN(1000)
```

```
root@mtbc-sonic-03-2700:/home/admin# ip link add neighbor_advertiser-1000 address 50:6b:4b:a3:53:80 type vxlan id 1000 local 10.1.0.32 remote 192.167.8.1 nolearning dstport 4789
Error: Attribute failed policy validation.
```

#### How I did it

vxlan_tunnel_name has to be less than IFNAMSIZ ie. (16) for the netdev creation to succeed

### CODE REVIEW

**Comment by vivekrnv** [comment]
@dgsudharsan @prsunny to review

**Review by dgsudharsan — APPROVED** [review]

**Comment by prsunny** [comment]
Is this master only issue?

**Comment by vivekrnv** [comment]
> Is this master only issue? How about 202012?

No, Can be in other labels

**Review by prsunny — APPROVED** [review]

**Comment by vivekrnv** [comment]
> Is this master only issue? How about 202012?

Update: @prsunny  test failure is not related to this.

**Pull request merged**
