### PR TITLE
Support disable/enable syslog rate limit feature

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Depends on PR https://github.com/sonic-net/sonic-buildimage/pull/17458

#### What I did

Add CLIs to enable/disable containercfgd to optimize warm/fast boot path

#### How I did it

Add CLIs to enable/disable containercfgd

#### How to verify it

unit test
manual test

### CODE REVIEW

**Comment by yxieca** [comment]
@Junchao-Mellanox can you add some unit test code?

**Comment by liat-grozovik** [comment]
@yxieca can you please help to review?

**Comment by liat-grozovik** [comment]
@Junchao-Mellanox should you add it to the command reference guide as a new command?

**Comment by Junchao-Mellanox** [comment]
> @Junchao-Mellanox should you add it to the command reference guide as a new command?

I already added it.

**Review by keboliu — APPROVED** [review]

**Review by yxieca — APPROVED** [review]

**Pull request merged**
