### PR TITLE
[202205][generate_dump]: Enhance show techsupport for cisco-8000 platform

### PR DESCRIPTION
**Pull request by gvlaemyn**
Signed-off-by: Geert Vlaemynck <gvlaemyn@cisco.com>

#### What I did

Added cisco-8000 specific platform information to "show techsupport" tarfile

#### How I did it

Added collect_cisco_8000 function to scripts/generate_dump which filters out the wanted files from /usr/share/sonic/device/${platform} and saves them in the techsupport tarfile under sai subdirectory

#### How to verify it

Run "show techsupport" and grep sai in the generated techsupport tarfile

### CODE REVIEW

**Comment by alpeshspatel** [comment]
@yxieca Can you please do the needful? This is a patch of #2403

**Review by yxieca — APPROVED** [review]

**Comment by alpeshspatel** [comment]
@yxieca  let us know if any action is required from our end

**Comment by yxieca** [comment]
> @yxieca let us know if any action is required from our end

@alpeshspatel can you address the test failure?

**Comment by gvlaemyn** [comment]
According to the test log below, the error in the test occurs in the python3 test environment setup: package version conflict for urllib3.
There’s nothing in the error log that refers to the new code from the PR.
 
https://dev.azure.com/mssonic/build/_build/results?buildId=181927&view=logs&j=32f6922a-c230-5b15-563e-3c6513093317&t=29c6fdfc-8469-5760-5066-e3c3a3a3d9cd&l=335
 
2022-12-01T18:31:34.5711680Z ##[section]Starting: Test Python 3
2022-12-01T18:31:34.5717485Z ==============================================================================
2022-12-01T18:31:34.5717774Z Task         : Command line
2022-12-01T18:31:34.5718039Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2022-12-01T18:31:34.5719047Z Version      : 2.212.0
2022-12-01T18:31:34.5719623Z Author       : Microsoft Corporation
2022-12-01T18:31:34.5720021Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
. . .
2022-12-01T18:31:51.0926299Z running build_ext
2022-12-01T18:31:51.2042463Z Traceback (most recent call last):
2022-12-01T18:31:51.2042802Z   File "setup.py", line 245, in <module>
2022-12-01T18:31:51.2043885Z     test_suite='setup.get_test_suite'
2022-12-01T18:31:51.2044665Z   File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 163, in setup
2022-12-01T18:31:51.2045446Z     return distutils.core.setup(**attrs)
2022-12-01T18:31:51.2046204Z   File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
2022-12-01T18:31:51.2046900Z     dist.run_commands()
2022-12-01T18:31:51.2047260Z   File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
2022-12-01T18:31:51.2047638Z     self.run_command(cmd)
2022-12-01T18:31:51.2047998Z   File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
2022-12-01T18:31:51.2048356Z     cmd_obj.run()
2022-12-01T18:31:51.2049076Z   File "/usr/local/lib/python3.7/dist-packages/ptr.py", line 208, in run
2022-12-01T18:31:51.2049613Z     with self.project_on_sys_path():
2022-12-01T18:31:51.2049940Z   File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
2022-12-01T18:31:51.2050633Z     return next(self.gen)
2022-12-01T18:31:51.2051478Z   File "/usr/local/lib/python3.7/dist-packages/setuptools/command/test.py", line 168, in project_on_sys_path
2022-12-01T18:31:51.2052133Z     require('%s==%s' % (ei_cmd.egg_name, ei_cmd.egg_version))
2022-12-01T18:31:51.2052776Z   File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 899, in require
2022-12-01T18:31:51.2053263Z     needed = self.resolve(parse_requirements(requirements))
2022-12-01T18:31:51.2054058Z   File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 790, in resolve
2022-12-01T18:31:51.2054665Z     raise VersionConflict(dist, req).with_context(dependent_req)
2022-12-01T18:31:51.2056127Z pkg_resources.ContextualVersionConflict: (urllib3 2.0.0a2 (/__w/1/s/.eggs/urllib3-2.0.0a2-py3.7.egg), Requirement.parse('urllib3<1.27,>=1.21.1'), {'requests'})
2022-12-01T18:31:51.2768758Z ##[error]Bash exited with code '1'.
2022-12-01T18:31:51.2873147Z ##[section]Finishing: Test Python 3

**Review by jhli-cisco — APPROVED** [review]

**Pull request merged**
