### PR TITLE
Support for aggregrate VOQ Counters.

### PR DESCRIPTION
**Pull request by vivekverma-arista**
#### What I did
Added CLI support for aggregate VOQ counters according to HLD [#1578](https://github.com/sonic-net/SONiC/pull/1587)

#### How I did it
Extended the existing CLI command `show queue counters [interface] --voq` for the SSI.

#### How to verify it
Sent traffic destined to egress out of different queues of a interface through multiple ingress interface chosen across FSIs and verified that the command displays the correct aggregate view of the counters  when run from the SSI

```
From FSI-3

admin@nfc404-3:~$ show queue counters "nfc404-3|Asic0|Ethernet4" --voq
                    Port    Voq    Counter/pkts    Counter/bytes    Drop/pkts    Drop/bytes
------------------------  -----  --------------  ---------------  -----------  ------------
nfc404-3|Asic0|Ethernet4   VOQ0              45            12386            0             0
nfc404-3|Asic0|Ethernet4   VOQ1               0                0            0             0
nfc404-3|Asic0|Ethernet4   VOQ2             204            10200            0             0
nfc404-3|Asic0|Ethernet4   VOQ3               0                0            0             0
nfc404-3|Asic0|Ethernet4   VOQ4              21             1050            0             0
nfc404-3|Asic0|Ethernet4   VOQ5               0                0            0             0
nfc404-3|Asic0|Ethernet4   VOQ6              29             1450            0             0
nfc404-3|Asic0|Ethernet4   VOQ7               0                0            0             0

```
```
From FSI-8

admin@nfc404-8:~$ show queue counters "nfc404-3|Asic0|Ethernet4" --voq
                    Port    Voq    Counter/pkts    Counter/bytes    Drop/pkts    Drop/bytes
------------------------  -----  --------------  ---------------  -----------  ------------
nfc404-3|Asic0|Ethernet4   VOQ0               0                0            0             0
nfc404-3|Asic0|Ethernet4   VOQ1               1               50            0             0
nfc404-3|Asic0|Ethernet4   VOQ2              51             2550            0             0
nfc404-3|Asic0|Ethernet4   VOQ3               0                0            0             0
nfc404-3|Asic0|Ethernet4   VOQ4              16              800            0             0
nfc404-3|Asic0|Ethernet4   VOQ5               0                0            0             0
nfc404-3|Asic0|Ethernet4   VOQ6             143             7150            0             0
nfc404-3|Asic0|Ethernet4   VOQ7               0                0            0             0
```

```
From SSI

admin@nfc404:~$ show queue counters "nfc404-3|Asic0|Ethernet4" --voq
                    Port    Voq    Counter/pkts    Counter/bytes    Drop/pkts    Drop/bytes
------------------------  -----  --------------  ---------------  -----------  ------------
nfc404-3|Asic0|Ethernet4   VOQ0              45            12386            0             0
nfc404-3|Asic0|Ethernet4   VOQ1               1               50            0             0
nfc404-3|Asic0|Ethernet4   VOQ2             255            12750            0             0
nfc404-3|Asic0|Ethernet4   VOQ3               0                0            0             0
nfc404-3|Asic0|Ethernet4   VOQ4              37             1850            0             0
nfc404-3|Asic0|Ethernet4   VOQ5               0                0            0             0
nfc404-3|Asic0|Ethernet4   VOQ6             172             8600            0             0
nfc404-3|Asic0|Ethernet4   VOQ7               0                0            0             0

```

#### New command output (if the output of a command-line utility has changed)
```
admin@nfc404:~$ show queue counters "nfc404-3|Asic0|Ethernet4" --voq
                    Port    Voq    Counter/pkts    Counter/bytes    Drop/pkts    Drop/bytes
------------------------  -----  --------------  ---------------  -----------  ------------
nfc404-3|Asic0|Ethernet4   VOQ0              45            12386            0             0
nfc404-3|Asic0|Ethernet4   VOQ1               1               50            0             0
nfc404-3|Asic0|Ethernet4   VOQ2             255            12750            0             0
nfc404-3|Asic0|Ethernet4   VOQ3               0                0            0             0
nfc404-3|Asic0|Ethernet4   VOQ4              37             1850            0             0
nfc404-3|Asic0|Ethernet4   VOQ5               0                0            0             0
nfc404-3|Asic0|Ethernet4   VOQ6             172             8600            0             0
nfc404-3|Asic0|Ethernet4   VOQ7               0                0            0             0
```

Should merge after [#908](https://github.com/sonic-net/sonic-swss-common/pull/908), [#20057](https://github.com/sonic-net/sonic-buildimage/pull/20057) and [#3271](https://github.com/sonic-net/sonic-swss/pull/3271)

Tracked by [#1543](https://github.com/sonic-net/SONiC/issues/1543)

HLD: [#1578](https://github.com/sonic-net/SONiC/pull/1587)

### CODE REVIEW

**Review by vmittal-msft — DISMISSED** [review]

**Comment by vmittal-msft** [comment]
@kenneth-arista @saksarav-nokia

**Comment by kenneth-arista** [comment]
@ysmanman @jfeng-arista

**Comment by kenneth-arista** [comment]
@arlakshm

**Comment by vivekverma-arista** [comment]
> 1. Based on my understanding,
> 
> * Sysport is the one where VoQ pointing to and we are aggregating the stats for ?
> * fap id is the source asics where we are getting the count and aggregating for all faps ?
> * idx is the VoQ id 0-7 ? or real VoQ id ?
> 
> 3. Do we support "show queue counter --voq" without any interface info ?
> 4. Can you please add test case for this ?

Yes the understanding of the key is correct. Refer https://github.com/vivekverma-arista/SONiC/blob/aggVoq/doc/voq/aggregate_voq_counters.md#database-changes for more details.

```show queue counter --voq``` is also supported on SSI and it will aggregate VOQ counters for all interfaces. The command is however not available for FSI.

**Comment by saksarav-nokia** [comment]
When the Line card is reset or goes offlline, are these counters cleared from SUP?.

**Comment by vivekverma-arista** [comment]
> When the Line card is reset or goes offlline, are these counters cleared from SUP?.

We are not doing anything explicit to clear this, but when the LC comes up online, it will overwrite the counters for it's own VOQs. 

swss changes -> https://github.com/sonic-net/sonic-swss/pull/3271

**Review by vmittal-msft — COMMENTED** [review]
We are waiting for HLD to be finalized before approving PRs.

**Comment by vivekverma-arista** [comment]
New PR raised as approach got changed: https://github.com/sonic-net/sonic-utilities/pull/3617

**Pull request closed without merging**
