### PR TITLE
Revert "Remove suppress-fib-pending CLI and make route_check.py check suppress-fib in BGP configuration"

### PR DESCRIPTION
**Pull request by dgsudharsan**
Reverts sonic-net/sonic-utilities#3331
BGP zebra enhancements is merged to master branch https://github.com/sonic-net/sonic-buildimage/pull/19717

Reverting the revert of bgp suppress pending feature to enable it in master branch

### CODE REVIEW

**Comment by dgsudharsan** [comment]
@stepanblyschak  plaese review

**Review by StormLiangMS — APPROVED** [review]
LGTM

**Comment by AnantKishorSharma** [comment]
Is there any plan to revert https://github.com/sonic-net/sonic-utilities/pull/3391 in 202405?

**Comment by rajendrat** [comment]
viz @kevinwangsk , need this in 202405

**Comment by dgsudharsan** [comment]
We should not be taking this change in 202405 as we don't have the required memory enhancements that are part of master only. From 202411 we will have fib suppression feature.

**Comment by AnantKishorSharma** [comment]
Hi @dgsudharsan , should we skip sonic mgmt test for this in 202405 in that case?

**Pull request merged**
