### PR TITLE
[chassis] Modify the show ip route to hide the Ethernet-IB port in the output

### PR DESCRIPTION
**Pull request by arlakshm**
#### What I did
Modify the show ip route to hide the Ethernet-IB port in the output
#### How I did it
- Ignore the route nexthop entry which has `Ethernet-IBx` as interface name
- update the output to indicate the route is learnt through iBGP
- 
#### How to verify it
Verify on voq chassis and UT

### CODE REVIEW

**Comment by BYGX-wcr** [comment]
The code changes look fine to me but the unit-test coverage metrics is not met.

**Review by BYGX-wcr — APPROVED** [review]
Looks good to me

**Comment by bingwang-ms** [comment]
@gechiang Is this change required for 202405 branch?

**Comment by gechiang** [comment]
> @gechiang Is this change required for 202405 branch?

Yes. this is needed.
Thanks!

**Pull request merged**
