### PR TITLE
[generate_dump] Revert "Revert generate_dump optimization PR's #2599", add fixes for empty /dump forder and symbolic links

### PR DESCRIPTION
**Pull request by vadymhlushko-mlnx**
#### What I did

1. [0ee19e5](https://github.com/sonic-net/sonic-utilities/commit/0ee19e55f946059a265551768a9b4b765c17f125) Revert [Revert the show-techsupport optimization PR's #2599](https://github.com/sonic-net/sonic-utilities/pull/2599)
2. [c8940ad](https://github.com/sonic-net/sonic-utilities/commit/c8940adec41c2c8432ae3eace5f06bfb881e4dd1) Add a fix for the empty `/dump` folder inside the final tar archive generated by the `show techsupport` CLI command.
3. [8a8668c](https://github.com/sonic-net/sonic-utilities/commit/8a8668c418868d2905afe99a9400a37a3a0a06be) Add a fix to not follow the symbolic links to avoid duplicate files inside the final tar archive generated by the `show techsupport` CLI command.

#### How I did it
Modify the `scripts/generate_dump` script.

#### How to verify it
1. Manual verification
- do the `show techsupport` CLI command and save output `original.tar.gz` (with original `generate_dump` script)
- do the `show techsupport` CLI command and save output `fixes.tar.gz` (with the `generate_dump` script modified by this PR)
- unpack both archives `original.tar.gz` and `fixes.tar.gz`
- compare both directories with `ncdu` & `diff --brief --recursive original fixes` Linux utilities

2. Run the community tests
- [sonic-mgmt/tests/show_techsupport](https://github.com/sonic-net/sonic-mgmt/tree/master/tests/show_techsupport)

### CODE REVIEW

**Comment by vivekrnv** [comment]
```
if $TAR -tf $TARFILE | grep $BASE/log/$(basename $file); then
    # If this path sits under "/var/log/" dir, the files
    # would've already been collected and thus just add a sym link
    if [ ! -z "${file##*.gz}" ]; then
        # files saved under log/ are zipped with gz
        file=$file.gz
    fi
    ${CMD_PREFIX}save_symlink ${file} sai_sdk_dump log
fi
```

I've used to check if the file is present in the TARFILE to add a symbolic link but now that we are removing the TARFILE append approach, i think this logic should also be updated

**Comment by vadymhlushko-mlnx** [comment]
> ```
> if $TAR -tf $TARFILE | grep $BASE/log/$(basename $file); then
>     # If this path sits under "/var/log/" dir, the files
>     # would've already been collected and thus just add a sym link
>     if [ ! -z "${file##*.gz}" ]; then
>         # files saved under log/ are zipped with gz
>         file=$file.gz
>     fi
>     ${CMD_PREFIX}save_symlink ${file} sai_sdk_dump log
> fi
> ```
> 
> I've used to check if the file is present in the TARFILE to add a symbolic link but now that we are removing the TARFILE append approach, i think this logic should also be updated

I've not completely removed the `tar append approach`.
I've put a function `save_to_tar()` (which will add everything to the final tar archive) before the `collect_mellanox_dfw_dumps()`. It means that your functionality working fine, because all the files that your function are expecting is already in the proper directory, so it could successfully create the symlinks. To verify - you could check the [commits/8a8668c418868d2905afe99a9400a37a3a0a06be](https://github.com/sonic-net/sonic-utilities/pull/2645/commits/8a8668c418868d2905afe99a9400a37a3a0a06be)

**Comment by vivekrnv** [comment]
> > ```
> > if $TAR -tf $TARFILE | grep $BASE/log/$(basename $file); then
> >     # If this path sits under "/var/log/" dir, the files
> >     # would've already been collected and thus just add a sym link
> >     if [ ! -z "${file##*.gz}" ]; then
> >         # files saved under log/ are zipped with gz
> >         file=$file.gz
> >     fi
> >     ${CMD_PREFIX}save_symlink ${file} sai_sdk_dump log
> > fi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I've used to check if the file is present in the TARFILE to add a symbolic link but now that we are removing the TARFILE append approach, i think this logic should also be updated
> 
> I've not completely removed the `tar append approach`. I've put a function `save_to_tar()` (which will add everything to the final tar archive) before the `collect_mellanox_dfw_dumps()`. It means that your functionality working fine, because all the files that your function are expecting is already in the proper directory, so it could successfully create the symlinks. To verify - you could check the [commits/8a8668c418868d2905afe99a9400a37a3a0a06be](https://github.com/sonic-net/sonic-utilities/pull/2645/commits/8a8668c418868d2905afe99a9400a37a3a0a06be)

Thanks for the update

**Comment by vivekrnv** [comment]
> > ```
> > if $TAR -tf $TARFILE | grep $BASE/log/$(basename $file); then
> >     # If this path sits under "/var/log/" dir, the files
> >     # would've already been collected and thus just add a sym link
> >     if [ ! -z "${file##*.gz}" ]; then
> >         # files saved under log/ are zipped with gz
> >         file=$file.gz
> >     fi
> >     ${CMD_PREFIX}save_symlink ${file} sai_sdk_dump log
> > fi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I've used to check if the file is present in the TARFILE to add a symbolic link but now that we are removing the TARFILE append approach, i think this logic should also be updated
> 
> I've not completely removed the `tar append approach`. I've put a function `save_to_tar()` (which will add everything to the final tar archive) before the `collect_mellanox_dfw_dumps()`. It means that your functionality working fine, because all the files that your function are expecting is already in the proper directory, so it could successfully create the symlinks. To verify - you could check the [commits/8a8668c418868d2905afe99a9400a37a3a0a06be](https://github.com/sonic-net/sonic-utilities/pull/2645/commits/8a8668c418868d2905afe99a9400a37a3a0a06be)

Ah, i see. Thanks for clarification.

**Review by vivekrnv — COMMENTED** [review]
Approved for the symbolic link changes

**Review by vivekrnv — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
